### ISSUE TITLE
Please add packages for php pecl pthreads for php54, php55u, php56u

### ISSUE THREAD

**Issue by jonathanvaughn** [iuscommunity/wishlist#10]
Please start providing php5[456][u]-pecl-pthreads packages - it's a pain to install manually using `pecl install pthreads` because the default `php` isn't ZTS enabled, and the pthreads pecl script doesn't check for `zts-php`, so I had to rename things around for `php`/`zts-php` and `php-config`/`zts-php-config` to build it (after which it works fine, and can rename things back).

pthreads can be handy for certain tasks, and since ZTS is already being built anyways, all the prerequisites are there, it'd just be nice to have a simple package to install instead of fighting with pecl every time I need to update or build a system... 

Thanks!

**Comment by carlgeorge** [comment]
Thanks for reaching out to us.  Here is our review process for new package requests.

* Is it a good fit for IUS?
* Is it maintainable with our current resources?
* After building the package, is the requester willing to test the package to ensure expected behavior?

I'm not yet familiar with this software, so I'm going to need some time to look into it before I can give you an answer.  I also need to investigate if there are any other dependencies we would have to build first.

Do you really use php54, php55u, and php56u?  It would simplify things if the request was just for one branch of PHP.

**Comment by jonathanvaughn** [comment]
We really do use all of the above - we do web development work for different clients who have different hosting providers / platforms / etc and thus a wide variety of PHP... we're still dragging one out of the PHP 5.2 stone age every now and then.

Our internal dev / QA servers are actually running all these versions of PHP via PHP-FPM or fastcgi inside of Docker containers, with some rather clever / frightening shell scripts and .htaccess php handler overrides to allow for any version to be used from both command line and web. Not a setup I would ever deploy to production, but for internal servers that can't be reached externally, it's not really an issue.

We used to build everything from scratch from source for every update, but once we got past maintaining 3 versions of PHP it got to be a bit much. Now I can just (usually) rebuild the docker images from Dockerfiles and restart the containers.

I'm not sure if pthreads has other dependencies that need building since we are including a wide range of packages already, but per https://php.net/manual/en/pthreads.requirements.php it just needs ZTS build which you already do (though sadly, as I indicated in my OP, it's pecl script isn't smart enough to find zts-php / zts-php-config on it's own, it assumes php / php-config).

**Comment by b-harper** [comment]
Hey jonathanvaughn,

I have made an initial php56u-pecl-pthreads RPM that will be hitting our testing repos after tonight's automation run.   If that package is working as excepted we can move on to other versions of PHP.

I have concerns about building new module for php54 given it will be EOL in about three months[0].  It is a balancing act in our time, the community's need and not enabling users to stay on old EOL versions of PHP.  It did not take that much time to create the php56u-pecl-pthreads package, as I was able to adapt it from Remi's package[1].  Until you requested this package, I had never heard of it.  I am not sure how much remand there is for this module.  At the same time, it does not get updated that often. 

Let us know how the  php56u-pecl-pthreads works.

-Ben
[0] http://php.net/supported-versions.php
[1] https://github.com/remicollet/remirepo/blob/b748aa3aa58473258b7ec2012bd74c5105b7b862/php/pecl/php-pecl-pthreads/php-pecl-pthreads.spec

**Comment by jonathanvaughn** [comment]
Thanks for working on this.

Even if the 5.4 package just goes to the archive repo in a few months, it would be nice to have it, but I would understand if you made a decision not to bother. 

I forget that 5.4 is already so close to EOL - we've only started recently seeing new clients with existing sites that are already on 5.4 (though we've upgraded many more from 5.2/5.3 over the last year or so), and haven't seen any on 5.5+. There's so much inertia with deployed projects, PHP can EOL a version, but we're still getting new clients who have PHP 5.2 sites that need support, and don't have the budget to upgrade any time soon (since often various extensions/modules to their sites need to be updated, etc because they won't work as-is on 5.3 much less 5.4, etc).

**Comment by b-harper** [comment]
It is unfortunate that PHP and other web technologies are in this position where EOL software is a requirement.  It is a hard sell to clients to upgrade, as the cost to upgrade is probably more than the initial deployment.  

Seeing that you do not have a PHP 5.6 environment for testing, I will work on getting some php55u-pecl-pthreads package in the testing repos.  


-Ben

**Comment by jonathanvaughn** [comment]
Actually, we do have a PHP 5.6 environment I could test drive the package on, though I might not be able to test it until later this week.

**Comment by b-harper** [comment]
Thanks for agreeing to test.  We won't push a requested package into the stable repos (and be on the hook to maintain it), until the requester has tested it.  With limited resources we want to prevent requests like, 'I don't have a use for package X, but it would be cool if it was in IUS'. 

In regards to test, we are looking for something like 'works for my use case' and not testing every feature.  


-Ben

**Comment by jonathanvaughn** [comment]
Well, no extensive testing yet, but it doesn't crash on a simple loop that spins up some threads, echos out the thread index's from the loop, and exits.

**Comment by b-harper** [comment]
Hey @jonathanvaughn,

Just wanted to check in and see if you had some time to do some testing.  Do you feel this package is good for the stable repos?  

-Ben

**Comment by jonathanvaughn** [comment]
Sorry I haven't had a chance to update on this. So far, no issues found, so it's probably safe to promote it to stable.

**Comment by b-harper** [comment]
Hey @jonathanvaughn,

Thanks for the feedback.  I'll get the ball rolling and the php55u-pecl-pthreads packages will hit the stable repos after tonight's automation run.  

-Ben
