### ISSUE TITLE
vmod-drupal7

### ISSUE THREAD

**Issue by gboddin** [iuscommunity/wishlist#100]
### What package do you want?

vmod-drupal7 4.0

### Why?
https://github.com/gboddin/edge-repo-dev/blob/vmod-drupal7/SPECS/vmod-drupal7.spec (they have it upstream) is already done, I was wondering if we could merge edge-repo and get rid of it.

This is a small varnish mod to compute drupal session's IDs for caching/filtering purpose. ( homepage https://git.kindwolf.org/libvmod-drupal7/ )

### OS versions

I would like this package for both RHEL 6 and 7.

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by b-harper** [comment]
Hey @gboddin,

Is this request tied to the request for [Varnish 5][0]?  If so, there does not appear to be a branch that supports Varnish 5, judging by the 3.0 and 4.0 branches.  

Looking over that project, I have concerns that I am unable to find a bug/issue/ticketing system to report issues.  Also, I am unable to find any versioned tarballs.  

[0]: https://github.com/iuscommunity/wishlist/issues/98

**Comment by gboddin** [comment]
Yes, the 4.0 branch is compatible with 5.0 and it was tied to it.

You're right, I will try to contact the maintainer (and previous colleague) to either move the project to gitlab/github or get included in varnish-modules ( might be too specific for that ).

**Comment by b-harper** [comment]
Based on my limited knowledge, it sounds like getting vmod-drupal7 into varnish-modules would be the ideal solution.  If that is not the case, seeing that vmod-drupal7 works with the version of Varnish in EPEL, then EPEL is the appropriate location for this request.

**Comment by b-harper** [comment]
I am clearing out stale issues and close them.  If this issues gets updated, we can open it again.
