### ISSUE TITLE
gearmand

### ISSUE THREAD

**Issue by gboddin** [iuscommunity/wishlist#101]
### What package do you want?

gearmand 1.1.12

### Why?

https://github.com/gboddin/edge-repo-dev/blob/vmod-drupal7/SPECS/gearmand.spec (they have it upstream) is already done, I was wondering if we could merge edge-repo and get rid of it..

### OS versions

I would like (maintain) this package for both RHEL 6 and 7.

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by b-harper** [comment]
Hey @gboddin,

Thanks for taking the time to submit this request.  I am curious why you need version 1.1.12.  Currently, EPEL7 has version 1.1.12 while EPEL6 only has 1.1.8.   Upstream is currently at [1.1.14][0].

It is important to note that EPEL is the appropriate repository for packages not provided by Red Hat.  IUS focuses on providing updated packages that are provided by Read Hat.   In some cases we have made exceptions, but that is only when an EPEL packages can not be updated per their policies.

The EPEL maintainers need to get contacted to see about getting EPEL6 version updated to 1.1.12 or both versions upgraded to 1.1.14.  

[0]: https://github.com/gearman/gearmand/releases/tag/1.1.14

**Comment by gboddin** [comment]
Yup indeed, I didn't check EPEL prior this closing this one!
