### ISSUE TITLE
python34u-paramiko and python35u-paramiko

### ISSUE THREAD

**Issue by raider700** [iuscommunity/wishlist#103]
### What package do you want?

python34u-paramiko
python35u-paramiko

### Why?

With the default paramiko of RHEL6 or RHEL7 the connection to a openssh server with version 6.7 or higher doen't work. As a result the connection fro RHEL to VMware6.0 or Debian8 doesn't work. Paramiko version 1.15.1 or higher is needet to get the connection working.

Bug in Paramiko Git: https://github.com/paramiko/paramiko/issues/423

RedHat refused to fix that behavior with the current releases.

### OS versions

I would like this package for both RHEL 6 and 7.

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by b-harper** [comment]
Hey @raider700,

Thanks for taking the time to submit this request.  Here are the current versions in EL6 and EL7:

EL6:
python-paramiko: 1.7.5
python-paramiko1.10: 1.10.1 (EPEL6)
openssh: 5.3

El7:
python-paramiko: 1.12.4
python2-paramiko: 1.16.1 (EPEL7)
openssh: 6.6


You mentioned that Red Hat has refused to fix this issue, but I am unable to find any bug that seems to support this claim.  I do see some inaction in a [fairly old request][0], [a new request][1], and [another new request][2].

Would paramiko also be broken from EL6 or EL7 to EL7 too?  If so, adding that information to those Red Hat bugs might help move things along.

Before we dig too deep into this request, can you confirm the EPEL7 and/or CentOS Cloud SIG versions work correctly.  A quick look reveals, there may be a fair amount of work needed to package all the requirements.

-Ben

[0]: https://bugzilla.redhat.com/show_bug.cgi?id=1196824
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1391887
[2]: https://bugzilla.redhat.com/show_bug.cgi?id=1391891

**Comment by raider700** [comment]
Hi @b-harper,

thank you for the reply.
We hat an RedHat support ticket for this issue: 01716051

The connection from EL6 to EL7 is working in both directions.
But both of them couldn't connect to a VMware6 or Debian8.
From a FC24 the connection to both is possible. 

A quick way to reproduce it:
-------------------------------------
[root@test log]# python
Python 2.6.6 (r266:84292, Aug  9 2016, 06:11:56) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import paramiko
>>> ssh = paramiko.SSHClient()
>>> ssh.connect('10.10.123.123',username='root',password='xxxxx')
No handlers could be found for logger "paramiko.transport"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/paramiko/client.py", line 295, in connect
    t.start_client()
  File "/usr/lib/python2.6/site-packages/paramiko/transport.py", line 451, in start_client
    raise e
paramiko.SSHException: Incompatible ssh peer (no acceptable kex algorithm)
>>> 
-------------------------------------

I will create a ticket in the redhat bugzilla soon.

Kindly regards,
Raider700

**Comment by raider700** [comment]
Ticket in the bugilla: https://bugzilla.redhat.com/show_bug.cgi?id=1405220

**Comment by raider700** [comment]
Ticket in the bugzilla seams to be ignored :)

We made a workaround in our scripts with normal scp command.
For me the request can be canceled but thx for the assistance.
