### ISSUE TITLE
haproxy17u

### ISSUE THREAD

**Issue by Fale** [iuscommunity/wishlist#113]
### What package do you want?

haproxy 1.7

### Why?

HAProxy 1.7 brings more reliability to HAProxy

### OS versions

I would like this package for RHEL 7.

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by carlwgeorge** [comment]
Howdy @Fale,

Thanks for opening this request with us.  This one was pretty straight forward.  The only thing worth mentioning is that I had to [diable lua support](https://github.com/iuscommunity-pkg/haproxy17u/commit/8e13c3ef8b798876e9a95697fc51f8c0a5fc2bc9) since it requires lua 5.3, which isn't available in RHEL 7.  We had to do the same thing for haproxy16u previously.  The initial build is complete and will move to our testing repositories during tonight's automation.

**Comment by Fale** [comment]
Thanks a lot, I'm going to test it tomorrow, then.

I'm a little sad we loose the lua part (I was interested in moving there some logics). I wonder if it would be possible to have it as well or it's impossible.

**Comment by carlwgeorge** [comment]
The only thing I know for sure is that haproxy's lua parts require lua 5.3, which isn't currently available in RHEL.  It may be possible to create a lua53u parallel library package and build against that, but that will take more research.  Let's get the initial package done first, and then we can look at adding lua support as a feature later.

**Comment by Fale** [comment]
I see :-).
I agree the best option would be to start testing and using it without lua and then figure out if/how to put lua

**Comment by Fale** [comment]
During this weekend I tested it with our configuration and everything worked as expected :) (also, I was pretty impressed that our haproxy 1.5 config works perfectly on 1.6 and 1.7 :))

**Comment by carlwgeorge** [comment]
Glad to hear it.  I'll go ahead and set the initial release [1.7.1-1](https://github.com/iuscommunity-pkg/haproxy17u/releases/tag/1.7.1-1) to move to the stable repositories tonight.

I was successful with lua53u and was able to build haproxy17u against it.  That will be in the [1.7.1-2](https://github.com/iuscommunity-pkg/haproxy17u/releases/tag/1.7.1-2) release, which will move to the testing repositories tonight.

**Comment by Fale** [comment]
I've pushed 1.7.1-1 in production and is keeping up well (with more than 5M sessions passed through it, I'm pretty confident :)). I'm using 1.7.1-2 with LUA in testing, and is behaving properly :). Green light from me

**Comment by carlwgeorge** [comment]
Thanks for the feedback, 1.7.1-2 (along with the lua53u dependency) will move to the stable repositories during tonight's automation.  Thanks for participating in IUS!
