### ISSUE TITLE
php71u-pecl-apcu_bc

### ISSUE THREAD

**Issue by nicjansma** [iuscommunity/wishlist#114]
### What package do you want?

php71u-pecl-apcu_bc

### Why?

[apcu_bc](https://github.com/krakjoe/apcu-bc) provides a backwards APC compatible API using APCu.

Since `php71u-pecl-apcu` is already available, it would be nice to have `php71u-pecl-apcu_bc`

### OS versions

I would like this package for CentOS 7.

### Testing

I agree to test the new package to ensure that it works as expected.

(I attempted to get `apcu_bc` installed on my CentOS 7 system using `pecl install apcu_bc` but couldn't figure out how to compile it for both `/usr/lib64/php/modules` and `/usr/lib64/php-zts/modules` since I'm using php-fpm)

**Comment by b-harper** [comment]
Hey @nicjansma,

Thanks for taking the time to contact us with this request.  IUS is forward looking and provides newer packages that developers consider to be stable.  On a case by case basis, we will make exceptions.  Currently, apcu_bc is marked as beta on the [pecl page][0].  

I have mixed thoughts on if we should make an exception for this package.  From what I can tell, this software is feature complete and has very little real bugs for the sizable amount of [downloads from pecl][1] alone.   That being said,  this software is not forward looking.  With all the changes from PHP 5 -> 7, should we provide a slim to the old ways?  

-Ben

[0]: https://pecl.php.net/package/apcu_bc
[1]: https://pecl.php.net/package-stats.php?pid=991&rid=&cid=3

**Comment by nicjansma** [comment]
@b-harper I've been using the package to avoid pains I found when migrating multiple websites when I decided to flip the hard switch to PHP7.

That said, I was able to figure out how to build this module relatively easy for myself:

```
pecl download apcu_bc
cd apcu_bc-1.0.3
zts-phpize
./configure --with-php-config=/usr/bin/zts-php-config
make && make test && make install
```

I would love to have it available in IUS, but feel free to close this if you don't think `apcu_bc` wouldn't be a good fit.

**Comment by ruben-herold** [comment]
@b-harper I would also like to see this package, cause many people will need it. Without it is impossible to use symfony2 apps. Please see: https://github.com/symfony/symfony/issues/20373

**Comment by b-harper** [comment]
Hey @ruben-herold,

Thanks for for providing some additional information.  When you speak of symfony2 apps, are you referring to php-symfony packages in EPEL?

**Comment by ruben-herold** [comment]
@b-harper yes thats the same problem with php7 all symfony2 versions have that problem, as described in the bug above. symfony team don't see it as bug ..

**Comment by ruben-herold** [comment]
@b-harper any news on this?

**Comment by carlwgeorge** [comment]
Despite the upstream beta status, we have decided to proceed with this request.  Maintaining compatibility with EPEL packages is a worthwhile end result.  Here is the [initial spec file](https://github.com/iuscommunity-pkg/php71u-pecl-apcu-bc/blob/1.0.3-1/SPECS/php71u-pecl-apcu-bc.spec).  The packages will move to the testing repositories during tonight's automation.

**Comment by ruben-herold** [comment]
@carlwgeorge thx a lot. I wil test it next week!

**Comment by ruben-herold** [comment]
@carlwgeorge It works here without any problem thx!

**Comment by carlwgeorge** [comment]
Thanks for the feedback.  The package will move to the stable repos during tonight's automation.
