### ISSUE TITLE
uwsgi-plugin-python36u

### ISSUE THREAD

**Issue by intgr** [iuscommunity/wishlist#116]
### What package do you want?

uwsgi-plugin-python36u 2.0.14

### Why?

I'd like to upgrade our uWSGI application to Python 3.6 soon and the uWSGI plugin is a requirement for that.

### OS versions

CentOS 7.

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by carlwgeorge** [comment]
This would be a great addition to IUS.  I've got the [spec file](https://github.com/iuscommunity-pkg/uwsgi-plugin-python36u) worked out, and builds are in progress.

**Comment by carlwgeorge** [comment]
All done, the initial release will move to the testing repositories during tonight's automation.  We look forward to your feedback on the package.

**Comment by intgr** [comment]
Thanks! Works fine so far. I will let you know if I discover any issues.

**Comment by carlwgeorge** [comment]
Thanks for the feedback.  This will move to our stable repositories during tonight's automation.  Thanks for participating in IUS!
