### ISSUE TITLE
python36u-lxml

### ISSUE THREAD

**Issue by intgr** [iuscommunity/wishlist#119]
### What package do you want?

python36u-lxml 3.7.2

### Why?

Please package the lxml module for Python 3.6.

PS: The python35u-lxml package is slightly out of date too (currently at 3.7.0).

### OS versions

CentOS 7.

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by carlwgeorge** [comment]
I have completed the [spec file](https://github.com/iuscommunity-pkg/python36u-lxml) and initial builds.  They will move to the testing repositories during tonight's automation.  Once that syncs to your local mirror, try it out and let us know how it goes for you.

**Comment by intgr** [comment]
Thanks! python36u-lxml from ius-testing works fine so far.

**Comment by b-harper** [comment]
@intgr,

Thanks for the feedback.  We will promote these packages to the stable repository during tonight's automation run.

-Ben
