### ISSUE TITLE
uwsgi-plugin-php56u

### ISSUE THREAD

**Issue by 00Asgaroth00** [iuscommunity/wishlist#120]
### What package do you want?

uwsgi-plugin-php56u

### Why?

I cannot install EPEL's edition of uwsgi with IUS's edition of php56u due to package dependencies. I did log a bug under the php56u package which was closed and i was pointed to making a wish here. EPEL's uwsgi-plugin-php depends on the system's php package (5.4.16) and is removed as soon as I install php56u.

### OS versions

CentOS 7.3 x64

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by carlwgeorge** [comment]
This should be fairly straightfoward.  Since we also package php56u for RHEL/Centos 6, would you be willing to test el6 packages of this as well?

**Comment by 00Asgaroth00** [comment]
I can test the CentOS 7 edition more quickly than the CentOS 6 version, however, I could fire up a VM with CentOS 6 and give it a test whirl for you too.

**Comment by carlwgeorge** [comment]
Excellent.  I've created the [spec file](https://github.com/iuscommunity-pkg/uwsgi-plugin-php56u), and the initial builds are complete.  The packages will move to the testing repository during tonight's automation.  After they propagate to your local mirror, try them out and let us know how it goes for you.

**Comment by 00Asgaroth00** [comment]
Excellent, thank you, I'll give them a test on monday and come back to you.

**Comment by 00Asgaroth00** [comment]
I can confirm that the testing repo, CentOS-7 x64 uwsgi-plugin-php56u rpm is working as expected with our current sites. Thanks for creating it.

I'll fire up a CentOS 6 vm and give the v6 rpm a test today, I'll come back to you on this one.

**Comment by 00Asgaroth00** [comment]
Hi, I can confirm that the testing repo, CentOS 6 x64, uwsgi-plugin-php56u rpm is working as expected for our test sites. Thank you for creating it.

**Comment by carlwgeorge** [comment]
Thanks for the testing feedback.  This package will move to the stable repositories during tonight's automation.  Thanks for contributing to IUS!
