### ISSUE TITLE
php71u-pear

### ISSUE THREAD

**Issue by jpackagejasonc** [iuscommunity/wishlist#121]
### What package do you want?

php71u-pear

### Why?

feature parity with php70u. not sure if oversight or if there's a good reason not to have the package. I couldn't find a reason so I filed this request.

### OS versions

I would like this package for CentOS 6

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by carlwgeorge** [comment]
Pear is pure PHP code, not compiled, so we are going to use a shared pear1u package for all future PHP stacks.  This was discussed in the [original request for php71u-pear](https://github.com/iuscommunity/wishlist/issues/104).  Next time, please [check for existing issues first](https://github.com/iuscommunity/wishlist/issues?q=is%3Aissue), as detailed in the [contributing guidelines](https://github.com/iuscommunity/wishlist/blob/master/CONTRIBUTING.md) for this repository.
