### ISSUE TITLE
stunnel 5.39

### ISSUE THREAD

**Issue by Xon** [iuscommunity/wishlist#123]
### What package do you want?

stunnel 5.39

### Why?

Centos6 only has stunnel 4.29 (2009) or Centos7 only has stunnel  4.56 (2013).

Significant update in feature set compared to stock.  For example; SOCKS proxy support, pre-shared key auth support. 4.29 lacks SNI, and a bunch of SSL options.

### OS versions

I would like this package for both RHEL 6 and 7.

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by b-harper** [comment]
@Xon,

Thanks for taking the time to submit this request.   As we look into what it would take to create and maintain stunnel packages, I am curious on your use case.  In this day in age where most client/server applications support SSL/TLS out of the box.

**Comment by Xon** [comment]
Frustratingly the nginx mail SMTP proxy module doesn't support SSL on the upstream leg. Obviously I can use something like ipsec/openvpn/ssh port forward/etc, but these have the trade off of significantly higher complexity.

**Comment by b-harper** [comment]
@Xon,

Thanks for the information.  Looking over some [nginx documentation][0], it would appear that SSL is supported.  Both the [EPEL 6][1] and [EPEL 7][2] version of nginx have been compiled with the '--mail_ssl_module' option. 

I just want to make sure you aren't jumping through unneeded hoops.


[0]: https://www.nginx.com/resources/admin-guide/mail-proxy/#mail_ssl
[1]: http://pkgs.fedoraproject.org/cgit/rpms/nginx.git/tree/nginx.spec?h=el6#n208
[2]: http://pkgs.fedoraproject.org/cgit/rpms/nginx.git/tree/nginx.spec?h=epel7#n230

**Comment by Xon** [comment]
@b-harper that is SSL termination of pop/imap/smtp connection, the upstream proxy connection between nginx and the backend is unencrypted. The nginx mail auth protocol is actually insufficient to-do proper verification as it just returns an IP to connect to and no common name to enable.

**Comment by b-harper** [comment]
@Xon, thanks for the clarification.  We will take a closer look at this request.

**Comment by b-harper** [comment]
I have started working on a spec file and it appears we won't run into any issue compiling stunnel on EL6 and EL7.  I assume that stunnel only supports the latest version and any breakage would come with a 6.x release, but I am [asking for confirmation][0].

[0]: http://www.stunnel.org/pipermail/stunnel-users/2017-January/005717.html

**Comment by b-harper** [comment]
It would appear that we are not going to get confirmation regarding stunnel's life cycle.  I assume that the stunnel project will only provides bug fixes and security updates for the latest tarball and incompatibilities would only be introduced in a 6.x release.  @Xon, would you agree with my assumptions?

I have created an [initial SPEC file][0] based on my assumptions and RPMs will be hitting the testing repositories during tonight's automation run.  @Xon, we look forward to getting feedback from you.  

[0]: https://github.com/iuscommunity-pkg/stunnel5u

**Comment by Xon** [comment]
@b-harper this like a reasonable assumption from what I've read of the release notes.

I should hopefully have feedback fairly quickly

**Comment by Xon** [comment]
@b-harper the 5.40 build has proven to be a drop-in replacement for 4.29 without any breaking configuration changes. I've started testing, but so far it looks like it is working properly :)

**Comment by b-harper** [comment]
I want to note that stunnel is open source software but is [not a community project][0].  Most software we package has an open development process along with a public bug tracker.   If we were to run into an issue with stunnel, it could be harder to get the issue addressed.  While I have some concerns regarding this, I do not feel these concerns should stop us from proceeding.

@Xon, thanks for the reply.  Based on your feedback, these packages will get moved to the stable repositories during tonight's automation run.

[0]: https://www.stunnel.org/index.html
