### ISSUE TITLE
python36u-mod_wsgi

### ISSUE THREAD

**Issue by robert-thompson** [iuscommunity/wishlist#126]
### What package do you want?

python36u-mod_wsgi

### Why?

There is a python35u-mod_wsgi package for python 3.5 so this request is to create one for python 3.6.

### OS versions

I would like this package for both CentOS and RHEL 7.

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by b-harper** [comment]
Hey @robert-thompson,

Thanks for taking the time to submit this request.  Some python36u-mod_wsgi packages would be a good fit for IUS.  We will look to get some initial packages built soon.

**Comment by b-harper** [comment]
Some initial packages have been built and will be available in the testing repositories after tonight's automation run.

**Comment by robert-thompson** [comment]
Looks like `/etc/httpd/conf.modules.d/10-wsgi-python3.6.conf ` is wrong; it is a binary tarball instead of ASCII text:
```
# file /etc/httpd/conf.modules.d/10-wsgi-python3.6.conf 
/etc/httpd/conf.modules.d/10-wsgi-python3.6.conf: gzip compressed data, was "dist/mod_wsgi-4.5.14.tar", last modified: Mon Jan 23 21:03:02 2017, max compression
#
```
This causes `httpd` to fail to start.

For reference, this is the the python35u one:
```
# file /etc/httpd/conf.modules.d/10-wsgi-python3.5.conf 
/etc/httpd/conf.modules.d/10-wsgi-python3.5.conf: ASCII text
#
```

**Comment by carlwgeorge** [comment]
Thanks for spotting that.  Fixed in [python36u-mod_wsgi-4.5.14-2](https://github.com/iuscommunity-pkg/python36u-mod_wsgi/releases/tag/4.5.14-2), which will move to our testing repositories during tonight's automation.

**Comment by robert-thompson** [comment]
Pulled down the new package and was able to get `mod_wsgi` working with `python36u-3.6.0-2`. Testing is 👍

Thanks

**Comment by carlwgeorge** [comment]
This package will move to the stable repos during tonight's automation.  Thanks for participating in IUS!
