### ISSUE TITLE
Python3.6 for RHEL6

### ISSUE THREAD

**Issue by mjholtkamp** [iuscommunity/wishlist#129]
### What package do you want?

python36u and friends

### Why?

python36u and friends are released for RHEL7, but not for RHEL6. Since our system is based on version 6 and we would like to use the newest python, we would like this to also be released for version 6.

### OS versions

I would like these packages for both RHEL 6 and 7.

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by b-harper** [comment]
Hey @mjholtkamp,

Thanks for taking the time to submit this request.  Please see [the note][0] regarding why EL6 was not included from the start.  It would appear that Python has corrected the sqlite issue.  We will give EL6 another look.

-Ben

[0]: https://github.com/iuscommunity/wishlist/issues/112

**Comment by carlwgeorge** [comment]
@mjholtkamp You're in luck, the minimum sqlite version was effectively removed in Python 3.6.1, which was [just released yesterday](https://www.python.org/downloads/release/python-361/).

**Comment by carlwgeorge** [comment]
Since this isn't a new package request, I'm going to close this in favor of iuscommunity-pkg/python36u#1.

**Comment by mjholtkamp** [comment]
Thanks for referring this issue to the right repository btw, I did not realize I could post it there. I'm tracking the issue there! 👍
