### ISSUE TITLE
Please provide php56u-xcache

### ISSUE THREAD

**Issue by Conan-Kudo** [iuscommunity/wishlist#13]
Could you please provide php56u-xcache? I use it as an alternative to the php56u-opcache because the tools I use were built around it (and the web-based admin that's available with it).

At one point in time, you provided php54u-xcache, and php-xcache is still actively developed. It also continues to be [packaged in Fedora](http://koji.fedoraproject.org/koji/packageinfo?packageID=15063), too.

**Comment by carlgeorge** [comment]
Howdy @Conan-Kudo,

Thanks for reaching out to us. Here is our standard review process for new package requests.

1. Is it a good fit for IUS?
2. Is it maintainable with our current resources?
3. After building the package, is the requester willing to test the package to ensure expected behavior?

Starting with [PHP 5.5.0](http://php.net/manual/en/migration55.new-features.php#migration55.new-features.opcache), opcache is now integrated into the main PHP source code.  What are the compelling reasons to use xcache over opcache?  I'm not very familiar with the differences or possible benefits.

**Comment by Conan-Kudo** [comment]
@carlgeorge 

Answering your questions point by point:
1. I believe it's a good fit because it complements the php packages you already provide. It provides a nice alternative cache for those who need/want it for using with php 5.6.
2. It should be maintainable with your current resources as a lot of the burden can be shouldered by Fedora. You can continue to track the Fedora package and keep maintaining the IUS variant based on those packaging scripts.
3. I'm certainly willing to test the package and ensure that it's working as it should.

As for why I need xcache over opcache, there are a couple of benefits:

* xcache is capable of caching var data, while opcache cannot
* xcache has an admin portal that can be used to monitor and manage the cache, while opcache operates without such a nicety

**Comment by carlgeorge** [comment]
Thank you for the thorough response.  It sounds like xcache has clear benefits.  I'll try to get some initial packages done for you today.

**Comment by carlgeorge** [comment]
Hey @Conan-Kudo, I had a question you may be able to help with.  The Fedora spec file has this in it.

```
%package -n xcache-admin
Summary:       XCache Administration
Requires:      mod_php, httpd
```

I'm guessing that this is the admin portal you were referring to.  Is the portal only compatible with mod_php and apache httpd?  Or can it work with alternate webservers that use php-fpm?

**Comment by carlgeorge** [comment]
On that same note, we need to come up with an alternate name for that subpackage.  Which of these names make the most sense?

* xcache-admin56u
* xcache56u-admin
* php56u-xcache-admin

**Comment by Conan-Kudo** [comment]
I do not believe it mandates mod_php and httpd, since php-xcache was developed by the folks at lighttpd. It should work fine with anything that offers PHP and web serving capabilities.

As for the alternate name, I would suggest "php56u-xcache-admin" as the appropriate option. It's a sane prefix.

**Comment by carlgeorge** [comment]
Initial packages have been built and will move to the testing repos during tonight's automation.  It may take up to 24 hours after that to sync to all mirrors, but you should be able to find them on the [master mirror](https://dl.iuscommunity.org/pub/ius/) tomorrow.

**Comment by carlgeorge** [comment]
@Conan-Kudo Have you had a chance to test this package yet?

**Comment by Conan-Kudo** [comment]
Sorry that I haven't got back to you earlier. I just got around to it, and it looks good to me. It works like I expected it to.

**Comment by carlgeorge** [comment]
Perfect.  The packages will move to the stable repositories during tonight's automation.  Thanks for participating in IUS!
