### ISSUE TITLE
uwsgi-plugin-php71u

### ISSUE THREAD

**Issue by divad** [iuscommunity/wishlist#131]
### What package do you want?

uwsgi-plugin-php71u

### Why?

IUS has uwsgi plugins for both PHP 5.6 and PHP 7.0, but not the latest and 'greatest' (hurhur) version of PHP, PHP 7.1, although IUS does ship a version of PHP 7.1. Adding this package would allow the use of the fabulous uwsgi server with the latest version of PHP.

### OS versions

I would like this package for RHEL 7.

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by carlwgeorge** [comment]
Howdy @divad,

I agree this would be a good addition for IUS.  I've completed the [spec file](https://github.com/iuscommunity-pkg/uwsgi-plugin-php71u) and the [initial build](https://github.com/iuscommunity-pkg/uwsgi-plugin-php71u/releases/tag/2.0.14-1) should move to our testing repositories during tonight's automation.

**Comment by divad** [comment]
I've tested it against uwsgi on RHEL7 and from my initial testing seems to work great:

![screenshot from 2017-03-29 13-02-39](https://cloud.githubusercontent.com/assets/747790/24453511/18e3032e-1480-11e7-9fd1-04737d90b332.png)

I'll install an application to test it further.

**Comment by divad** [comment]
Dokuwiki (latest) works great using nginx + uwsgi + php71u :D

**Comment by carlwgeorge** [comment]
Excellent, thanks for the quick feedback.  The package will move to the stable repos during tonight's automation.  Thanks for participating in IUS!
