### ISSUE TITLE
Missing ius archive centos 5 repodata

### ISSUE THREAD

**Issue by chasersrush** [iuscommunity/wishlist#134]
Reporting that https://dl.iuscommunity.org/pub/ius/archive/CentOS/5/i386/repodata/repomd.xml is missing.

Please could someone fix it.

Thanks

**Comment by b-harper** [comment]
Hey @chasersrush,

Please see [this thread][0], regarding the status of EL5.

[0]: https://github.com/iuscommunity/announce/issues/4
