### ISSUE TITLE
php70u-pecl-mongodb

### ISSUE THREAD

**Issue by jamiel** [iuscommunity/wishlist#136]
### What package do you want?

php70u-pecl-mongodb

### Why?

Same reasons as detailed in #130, where this was created for php71u but not ported to php70u.

### OS versions

I would like this package for both RHEL 6 and 7.

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by b-harper** [comment]
Hey @jamiel,

Thanks for taking the time to submit this request.  Seeing that we already package the mongodb module for php71u, a package for php70u is a good fit for IUS.  An initial [spec file][0] has been created and packages will hitting the testing repositories during tonight's automation run. 

[0]: https://github.com/iuscommunity-pkg/php70u-pecl-mongodb

**Comment by b-harper** [comment]
I noticed a slight error with the initial packages.  Updating packages are getting built.

**Comment by b-harper** [comment]
A new version of module was released yesterday.  The testing repositories now contains the latest packages with the fix for the issue I noticed yesterday.

**Comment by jamiel** [comment]
Thank you. On my initial tests this appears to be working as expected.

Tested on CentOS 6 x86_64.

**Comment by b-harper** [comment]
@jamiel,

Thanks for the feedback.  The packages will be moved into the stable repositories during tonight's automation run.
