### ISSUE TITLE
tmux 2.4

### ISSUE THREAD

**Issue by stephenl03** [iuscommunity/wishlist#137]
### What package do you want?

tmux 2.4

### Why?

There have been major changes between 1.X and 2.X along with many bug fixes. Options have been added and others have been removed.

### OS versions

I would like this package for both RHEL/CentOS 6 and 7.

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by carlwgeorge** [comment]
[package source](https://github.com/iuscommunity-pkg/tmux2u)

The initial build will move to the testing repos during tonight's automation.  We look forward to your feedback.

**Comment by stephenl03** [comment]
Everything looks good. I have tested the install on a few systems without issues.

**Comment by b-harper** [comment]
@stephenl03,

Thanks for the feedback.  These packages will get moved into the stable repositories during tonight's automation run.
