### ISSUE TITLE
mailman 2.1.24

### ISSUE THREAD

**Issue by ricucu** [iuscommunity/wishlist#140]
### What package do you want?

Mailman 2.1.24

### Why?

It is about the way mailman mitigates issues around DMARC. This has been properly addressed in Mailman 2.1.22, but RHEL 7 only includes mailman 2.1.15. Fedora includes 2.1.21. Anything over 2.1.22 has all the DMARC functionality we need (https://mail.python.org/pipermail/mailman-announce/2016-April/000224.html)

### OS versions

I would like this package for CentOS 7.

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by carlwgeorge** [comment]
What you are asking for appears to be only a slightly newer version, so we should first ask Red Hat to either 1) rebase the EL7 package from 2.1.15 -> 2.1.22+, or 2) backport the DMARC support to their 2.1.15 package.  I don't know if (1) will be successful or not seeing as not even Fedora has that version yet.  There is an [open bug](https://bugzilla.redhat.com/show_bug.cgi?id=1304360), but it doesn't explain why it's delayed.  Would you mind opening a bug with Red Hat for EL7 and linking it here?

bug form: https://bugzilla.redhat.com/enter_bug.cgi?product=Red%20Hat%20Enterprise%20Linux%207&component=mailman&version=7.3

**Comment by ricucu** [comment]
Hi, upon more investigation, I realised that the DMARC features that really make a difference are not in the 2.1.22+, but in Mailman 3. So, my mistake, I will close this issue.
