### ISSUE TITLE
python36u-django

### ISSUE THREAD

**Issue by gebailey** [iuscommunity/wishlist#142]
### What package do you want?

python36u-django-1.11.2 or later

### Why?

Development of Django applications on CentOS 7 is cumbersome as EPEL only has python-django 1.6, which is no longer supported as of April 2015.  I already use IUS packages for python, and having an installable django RPM would greatly simplify the development and deployment of Django applications.  Providing this as a python35u instead of a python36u package is fine too.

### OS versions

I would like this package for RHEL 7.

### Testing

I agree to test the new package to ensure that it works as expected.

### Other

Is there documentation or tools that exist that help users of IUS repo packages create RPMs of python35u or python36u modules?  I'm a Fedora packager, and would be interested in knowing what guidelines are processes are used to port Fedora packages to IUS.

**Comment by b-harper** [comment]
Hey @gebailey,  

Thanks for taking the time to submit this request.  Typically, IUS only provides updated packages found in EL.  EPEL is the appropriate location for packages not in EL.   In some cases, we have provided packages that are in EPEL but only after it is clear that the EPEL package can not get updated.  Here is the [current discussion][0] regarding updating django in EPEL. 

Currently, all of our documentation is geared toward the end user.  The technical execution of our [philosophy][1] and [SafeRepo initiative][2] can vary from package to package.  Look for a commit like 'Port from Fedora to IUS' from any our [python36u modules][3] to get an idea on what we do when porting a Fedora python module.  


[0]: https://bugzilla.redhat.com/show_bug.cgi?id=1432365
[1]: https://ius.io/Philosophy/#philosophy
[2]: https://ius.io/SafeRepo/#the-saferepo-initiative
[3]: https://github.com/iuscommunity-pkg?utf8=✓&q=python36u&type=&language=

**Comment by b-harper** [comment]
I am starting to gather some information about this request.  Django's [download page][0] has some excellent versioning and life cycle information.  @gebailey, was there a particular version you were looking for?  Looks like the first pure python 3 release won't be out til the end of the year.  

Looking over Fedora's spec file, there are a number of build requirements.  Also, there are a number of Django modules in Fedora.  @gebailey, do you just need Django or do you also need some Django modules as well?  It has been awhile since I have messed with Django and I do not know if there are a hand full of modules that are considered critical.  The number of build requirements and modules need to be factored in when evaluating a new package request.  


[0]:  https://www.djangoproject.com/download/

**Comment by gebailey** [comment]
> In some cases, we have provided packages that are in EPEL but only after it is clear that the EPEL package can not get updated.

Yes, it appeared that EPEL was stuck with python-django 1.8 for some reason, and I wanted to start with something newer (and supported).

> Look for a commit like 'Port from Fedora to IUS'

This is great; I wasn't aware that you imported the Fedora git repo first!

> was there a particular version you were looking for?

I was thinking 1.11, since that's the current LTS release, from what I can see on the [Download Django](https://www.djangoproject.com/download/) page.

> do you just need Django or do you also need some Django modules as well?

I don't need any specific Django modules, but I see that Django itself requires the pytz module.  I didn't see an existing `python36u-pytz` package that supplied that.

> The number of build requirements and modules need to be factored in when evaluating a new package request.

Understood.  I had a go at creating `python36u-pytz` and `python36u-django`, and was mostly successful, except that I couldn't get the tests to run correctly, and I used `pip install` at RPM build time to install and configure sphinx to build the documentation, because the existing version of sphinx on CentOS 7 produced errors when processing the documentation.

**Comment by b-harper** [comment]
@gebailey,

Thanks for additional information about your needs.  I have not had a chance to dig too deep into this request yet.  For the most part, I have only given the Fedora spec file a quick glance.  I am curious how you were able to cut down all the BuildRequires to just pytz.

Also, I think we should explore if we could package this so that it could work with all version of python3, not just 3.6.

**Comment by carlwgeorge** [comment]
Django installs into the site-packages directory like other Python modules, so the file paths will all be specific to the MAJOR.MINOR version of Python it was installed with.  Because of this I don't think it will be possible to create a django package that works for multiple versions of Python 3.

**Comment by b-harper** [comment]
Another option for newer Django packages is the [CentOS OpenStack SIG][0].  It offers Django 1.8.7 for stock python.  I just wanted to note this, as I tend to forget about CentOS SIGs.


[0]: http://mirror.centos.org/centos/7/cloud/x86_64/openstack-mitaka/

**Comment by gebailey** [comment]
> I am curious how you were able to cut down all the BuildRequires to just pytz.

Apologies if I miscommunicated; I meant to state that Django would have a *Requires* of `python35u-pytz` or `python36u-pytz` (which I didn't see).

> Another option for newer Django packages is the CentOS OpenStack SIG.

Ah, hadn't yet seen that one.  Thanks for the pointer.

**Comment by b-harper** [comment]
@gebailey, thanks for the update.  It does appear django has a rat's nest of dependencies that would need to be built.  Generally, we tend to shy away from modules that have a long list of dependencies as the long tale of support can get tricky.  One time, we were put into a [tough spot with libmemcached][0] which was a requirement for a PHP module.  


[0]: https://github.com/iuscommunity/wishlist/issues/34#issuecomment-302728082

**Comment by gebailey** [comment]
> It does appear django has a rat's nest of dependencies that would need to be built. Generally, we tend to shy away from modules that have a long list of dependencies as the long tale of support can get tricky.

Understood; thanks for your consideration and the useful links to other potential resources!
