### ISSUE TITLE
libmemcached 1.0.18

### ISSUE THREAD

**Issue by gotyaoi** [iuscommunity/wishlist#143]
### What package do you want?

libmemcached 1.0.18

### Why?

The current packaged version of libmemcached in IUS is 1.0.16. This version contains a bug that introduces 5 second latency on some requests when using php56u-pecl-memcached 2.2.0, also from IUS. Testing with a manually installed libmemcached 1.0.18 resolved the issue. Additionally, the github readme of pecl-memcached states that:
> libmemcached version 1.0.18 or higher is recommended for best performance and compatibility with memcached servers.

So if php56u-pecl-memcached was ever to be updated, an update to libmemcached would probably be required as well.

### OS versions

Our use case is only for CentOS 6 at the moment

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by b-harper** [comment]
Hey @gotyaoi,

This repository is only for new package requests.  Please file any bugs and/or requests in the  repository for the package in question.  In regards to libmemcached 1.0.18, please see [this issue][0].


[0]: https://github.com/iuscommunity-pkg/libmemcached10/issues/1

**Comment by gotyaoi** [comment]
Ah, my mistake, sorry about that. From the contributing page on the site, I wasn't sure about the distinction between new packages and new versions of existing packages.

**Comment by b-harper** [comment]
@gotyaoi, thanks for that feedback.  We might need to look into improving the wording on that page to prevent confusion.
