### ISSUE TITLE
php70u-pecl-redis igbinary support

### ISSUE THREAD

**Issue by tvandervorm** [iuscommunity/wishlist#146]
### What new package do you want?

php70u-pecl-redis _with igbinary support_

### Why?

Currently php70u-pecl-redis only supports the builtin php serializer, to enable use of the igbinary serializer (which offers better performance) a compile flag is needed: --enable-redis-igbinary

(see https://github.com/phpredis/phpredis#installation)

I don't know if compiling with this flag creates a dependency on the igbinary package, if so perhaps a separate version that has been compiled with this flag could be created?

### OS versions

I would like this package for RHEL 7.

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by carlwgeorge** [comment]
Please open an issue on the [package source repo](https://github.com/iuscommunity-pkg/php70u-pecl-redis).

**Comment by carlwgeorge** [comment]
@tvandervorm FYI I've got a build going to add igbinary support, I just want to track it in the right place for future reference.

**Comment by tvandervorm** [comment]
@carlwgeorge done: https://github.com/iuscommunity-pkg/php70u-pecl-redis/issues/1

(thanks for the quick reply)
