### ISSUE TITLE
suhosin for php 7.x

### ISSUE THREAD

**Issue by smuckola** [iuscommunity/wishlist#147]
### What new package do you want?

suhosin for php 7.x. This is a two-part security component for php, consisting of a hardening patch for php's core and a module for php. Either part is optional, and helps to protect the entire system against known and unknown bugs in php or any php-based apps.

https://suhosin.org/stories/download.html

### Why?

You've packaged suhosin for php 5 so it should be updated for php security. I don't know if you (or fedora) provided the hardening patch to PHP itself, or just the module.  But even just the module is good. Thank you.

### OS versions

I would like this package for CentOS 7.

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by b-harper** [comment]
Hey @smuckola,

Thanks for taking the time to submit this issue.  IUS stands for 'Inline with Upstream Stable'.  Currently, the [README][0] for the PHP7 repository states it is pre-alpha and should not be run in production.  If/when suhosin releases a stable version for PHP7, we can reconsider this request. 


[0]: https://github.com/sektioneins/suhosin7/blob/41c41d7f53ea7579bc22d0da6b468f22890aadb6/README.md
