### ISSUE TITLE
FreeIPA 4.5.3

### ISSUE THREAD

**Issue by datakid** [iuscommunity/wishlist#148]
### What new package do you want?

FreeIPA 4.5.3

### Why?

CentOS/EPEL ships with 4.4.0 which is not available any more on the FreeIPA website. 

There are a number of important updates - 4 point releases of 4.4.x and three of 4.5.x in a year of development, including some security and some system security (ipa-replica, in particular, is now more stable)

### OS versions

I would like this package for CentOS 7.

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by b-harper** [comment]
Hey @datakid,

Thanks for taking the time to submit this request.  You mainly focus on security for your reasoning for wanting an updated version.  I wanted to make sure you were aware of [Red Hat's backporting of security fixes][0] before we look too much into this request. 

[0]: https://access.redhat.com/security/updates/backporting/?sc_cid=3093

**Comment by datakid** [comment]
There are a number of updates, given that FreeIPA is an authentication system a lot of them will be security by definition. By system security I meant that without ipa-replica, our IPA server has no secondary.

In reality there are a bunch of updates that we are interested in - including but not limited to ipa-replica working and having short logins.

**Comment by b-harper** [comment]
@datakid,

Thanks for the clarification.  We will take a look and report back.

**Comment by evaryont** [comment]
I'd be also willing to test FreeIPA 4.5!

**Comment by carlwgeorge** [comment]
RHEL 7.4 has rebased ipa to 4.5, so I don't believe this is still necessary.

* https://access.redhat.com/errata/RHBA-2017:2304
* https://bugzilla.redhat.com/show_bug.cgi?id=1392858
* https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Linux_Domain_Identity_Authentication_and_Policy_Guide/install-replica.html
