### ISSUE TITLE
Please provide python34u-zmq

### ISSUE THREAD

**Issue by kichuku** [iuscommunity/wishlist#15]

**Comment by b-harper** [comment]
Hey @kichuku,

It was nice chatting with your in IRC on Friday.  You were working on a personal project to see if you could get GNS3[0] working on CentOS.  After a few bumps along the way. you let us know that you got it installed and it sounds like you do not need these package after all.

-Ben

[0] http://www.gns3.com/

**Comment by kichuku** [comment]
Yes. And I should thank you for the help that you provided that day. And I was able to get gns3 running without this package.
