### ISSUE TITLE
php71u-pecl-amqp

### ISSUE THREAD

**Issue by allangomesptc** [iuscommunity/wishlist#151]
### What new package do you want?

php71u-pecl-amqp

### Why?

I'm updating from php70u that has php70u-pecl-amqp in repository to php71u. However, this new repository 7.1 doesn't have the package  php71u-pecl-amqp needed by my application.
I've checked the version of amqp in php70u-pecl-amqp and it seems that is the newest version of amqp. It may just a repack for php7.1.
OS: CentOS 7

### Testing

I agree to test the new package to ensure that it works as expected.

Thanks in advance!

**Comment by carlwgeorge** [comment]
Hello @allangomesptc.  This package seems like a great fit.  I've completed the [spec file](https://github.com/iuscommunity-pkg/php71u-pecl-amqp) and the built packages will move to the testing repos during tonight's automation.  Let us know once you have a chance to install and test them.

**Comment by allangomesptc** [comment]
Thak you @carlwgeorge. I will let you know when I have the tests finished.

**Comment by allangomesptc** [comment]
Hello,

   We are using the package in staging environment and all tests are good.
   I believe everything is fine.

Thanks so much

**Comment by b-harper** [comment]
@allangomesptc,

Thanks for the feedback.  The packages will be moved the to stable repositories during tonight's automation run.
