### ISSUE TITLE
Postfix 3.2.2

### ISSUE THREAD

**Issue by evaryont** [iuscommunity/wishlist#153]
### What new package do you want?

Postfix 3.2.2

### Why?

CentOS 7 currently packages Postfix 2.10.1 which is EOL'd by upstream as of the [release of 3.2](http://www.postfix.org/announcements/postfix-3.2.0.html), released this past February.

### Testing

I agree to test the new package to ensure that it works as expected. All of my servers run postfix, either as a mail server or relaying system mail.

There was previously #9, though that was closed a couple of years ago.

**Comment by carlwgeorge** [comment]
You can still comment on #9, we can re-open it if needed.  Let's continue the conversation over there.
