### ISSUE TITLE
php71u-pecl-yaml

### ISSUE THREAD

**Issue by akinspe** [iuscommunity/wishlist#154]
### What new package do you want?

php71u-pecl-yaml

### Why?

php56u-pecl-yaml exists, however there is no corresponding version for 7.1 (or 7.0 for that matter)

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by b-harper** [comment]
Hey @akinspe,

Thanks for reaching out.  Typically, we don't blindly rebuild all modules for a new version of PHP or python.  Also, modules took a fair amount of time to make the needed changes to work under PHP7.  

We will work on getting some php71u-pecl-yaml packages built.

**Comment by akinspe** [comment]
Thanks! It looks like your standard PECL spec template should work. I altered it and used YAML 2.0.2 and were able to build it successfully. It's a synthesis of the YAML template and other PHP 7 pecl templates.  We would just like it to be in the repository. I've created a preliminary spec here: https://gist.github.com/akinspe/4883779809507b7d7bb19768f6e030bf

I'm happy to help in any other way I can. Thanks again.

**Comment by b-harper** [comment]
Thanks for posting the spec file.  I was almost done reforking Fedora's spec file, when I noticed your comment.  There are few tweaks and a patch, see [php71u-pecl-yaml.spec][0].

Packages have been built and will hit the testing repositories during tonight's automation run.  



[0]: https://github.com/iuscommunity-pkg/php71u-pecl-yaml/blob/master/SPECS/php71u-pecl-yaml.spec

**Comment by akinspe** [comment]
Great. Thanks. We'll try it out and let you know how it goes.

**Comment by akinspe** [comment]
This is working great for us. It has passed all of our tests. Thanks for the work. Is there something else you'd like us to do to move this into the main repo?

**Comment by b-harper** [comment]
@akinspe,

Thanks for the feedback.  That is all we need.  The packages will get moved to the stable repositories during tonight's automation run.
