### ISSUE TITLE
httpd24u-mod_myfixip

### ISSUE THREAD

**Issue by raider700** [iuscommunity/wishlist#157]
### What new package do you want?

Apache Module: proxy-protocol

### Why?

When using a haproxy (tcp mode) before an reverseproxy cluster it would be nice to get the real ip address to the apache for some ip based configurations and logging.

About the proxy-protocol:
The haproxy includes a protocol to send the real ip when the connection to the backend is established. The apache module proxy_protocol can read this header and use the real ip internal.
https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt

About the Apache module:
https://github.com/roadrunner2/mod-proxy-protocol

Spec files for redhat/centos
https://github.com/earsdown/mod-proxy-protocol/tree/rpmbuild/redhat

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by b-harper** [comment]
Hey @raider700,

Thanks for reaching out.  I have briefly started looking into this request, as I would have thought this feature would already exist in httpd.   Support for Proxy Protocol will be added to [mod_remoteip in 2.5][0].  The HAProxy [blog post][1]  mentioned using [mod_fixmyip][2], but both mod_proxy_protocol and mod_fixmyip are mentioned in the comments.  They both have open issues about http2 support.  Does your use case involve http2?



[0]: https://httpd.apache.org/docs/trunk/mod/mod_remoteip.html
[1]: https://web.archive.org/web/20161024161315/http://blog.haproxy.com/haproxy/proxy-protocol/
[2]: https://github.com/ggrandes/apache22-modules/blob/master/mod_myfixip.c

**Comment by raider700** [comment]
Hi @b-harper,

thank you for looking into the request and the information.
At the moment we don't use http2 on any of our server.

The mod_fixmyip sounds also useful for us.
We would be happy with any of them as package.

Kindly regards,
Raider700

**Comment by b-harper** [comment]
Hey @raider700,

Thanks for the update.  I think it would make more sense to go with mod_fixmyip as it is listed in the blog post and has [some form of versioning][0].  Have you used either of these modules before, just curious if one is better than the other?


[0]: https://github.com/ggrandes/apache22-modules/blob/master/mod_myfixip.c#L4-L19

**Comment by b-harper** [comment]
An initial httpd24u-mod_myfixip [spec file][0] has been created and packages will hit the testing repositories during tonight's automation run.  @raider700, let us know if they work for your needs. 

[0]: https://github.com/iuscommunity-pkg/httpd24u-mod_myfixip

**Comment by raider700** [comment]
Hi @b-harper,

thanks for the efforts and the package.
First tests are working and we scheduled a usage in dev-stage next week.

I will inform you as soon as possible.

Kindly regards,
Raider700

**Comment by oogali** [comment]
@raider700 Any updates?

**Comment by b-harper** [comment]
@raider700 or others,

Just checking in to see if the package looks good.  If so, we can move it to the stable repositories.

**Comment by b-harper** [comment]
@raider700, @oogali or others,

I wanted to see if there was still interest in this package.  If not, we will remove the package from the testing repositories and close this issue.

**Comment by oogali** [comment]
From me? No.

Sometimes people forget about open issues, so I was just trying to help out by keeping up the "pressure" on feedback. That way you could more easily make a decision to proceed or close the issue.

**Comment by b-harper** [comment]
It would appear that @raider700 or others no longer need this package.  The package will be removed from the testing repositories after tonight's automation run.  This issue can be reopened if we get interest again.
