### ISSUE TITLE
openssl

### ISSUE THREAD

**Issue by morphine00** [iuscommunity/wishlist#160]
### What new package do you want?

openssl

### Why?

For webserving, to go with Apache. The availability of ciphers for use in HTTPS depends on OpenSSL. Also, the proper negotiation (ALPN) for using HTTP/2 is _also_ OpenSSL-dependant. For example, I set up HTTP/2 support in Apache 2.4 IUS just fine, only to find out that browsers weren't using it because it needed ALPN which needs OpenSSL 1.0.2 at least.

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by b-harper** [comment]
Hey @morphine00,

Please see #70.

**Comment by morphine00** [comment]
Ah, that's a bummer.
