### ISSUE TITLE
php72u

### ISSUE THREAD

**Issue by xarr** [iuscommunity/wishlist#163]
### What new package do you want?

PHP 7.2
(Announcement: http://news.php.net/php.announce/230)

### Why?

PHP has naturally always been a strong fit for IUS and see no reason why release 7.2 should be any different. I'd be absolutely shocked if you guys weren't already secretly working on this!

### Testing

I agree to test the new package to ensure that it works as expected.

### Thoughts

I think the previous structure / naming convention ("mod_php72u") has worked well in the past and will continue to serve the IUS community well. I'd be happy to open issues for all the corresponding (albeit necessary) modules/extensions.

### And finally...

Thank you for all your efforts--IUS rocks!

**Comment by b-harper** [comment]
Hey @xarr,

Thanks for submitting this issue.  As you mentioned, PHP 7.2 is on our radar.  As soon as we got some packages ready for the testing repositories, we will update this issue.

**Comment by karljohns0n** [comment]
Please include php72u-pecl-memcached at the same time.

**Comment by b-harper** [comment]
@karljohns0n, 

Please submit a new issue for php72u-pecl-memcached so we can track progress separately.

**Comment by b-harper** [comment]
I wanted to give a progress upgrade.  

PHP 7.2 introduces some new features and some of them have new build requirements.  [Argon2 Password Hash][0] requires libargon2-devel and [new sodium extension][1] requires libsodium-devel.  The argon2 packages aren't in EL 7 or EPEL7.  On the other hand, EPEL7 has the libsodium packages, just not a new enough version.  We are currently working on getting updated or new packages into EPEL7.  

My guess is we will not see php72u packages till 2018.

[0]: https://wiki.php.net/rfc/argon2_password_hash
[1]: https://wiki.php.net/rfc/libsodium

**Comment by b-harper** [comment]
It is time for another progress update.

Argon2 packages have made their way into [EPEL7][0].

We are [still working through][1] the best way to get updated libsodium-devel packages.


[0]: https://bugzilla.redhat.com/show_bug.cgi?id=1523340
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1524551

**Comment by b-harper** [comment]
Here is EPEL package request for [libsodium13][0].  Once this package get accepted into EPEL, the current libsodium would get updated to a newer version which is required by PHP 7.2.


[0]: https://bugzilla.redhat.com/show_bug.cgi?id=1532772

**Comment by carlwgeorge** [comment]
The [EPEL update for libsodium and libsodium13](https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2018-93f737b65e) has been pushed to the epel-testing repository.

**Comment by b-harper** [comment]
Some initial packages have been built and will hit the testing repositories after tonight's automation run.  Note, we enabled EPEL testing to bring in the libsodium-devel build requirement sooner.  We typically do not built against EPEL testing and are confident that libsodium will not change before making to stable EPEL.  If that happens, we might need to build new packages.

Lets us know if these package work for your needs.

**Comment by xarr** [comment]
**Confirmed working**--although my preliminary testing is minimalist at best:

```
# cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)
```

```
# rpm -qa | grep php72u
php72u-common-7.2.1-1.ius.centos7.x86_64
php72u-cli-7.2.1-1.ius.centos7.x86_64
php72u-opcache-7.2.1-1.ius.centos7.x86_64
mod_php72u-7.2.1-1.ius.centos7.x86_64

# php -v
PHP 7.2.1 (cli) (built: Jan 22 2018 13:22:57) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.2.1, Copyright (c) 1999-2017, by Zend Technologies
```

`php72u-sodium` loaded successfully as well (in conjunction with `libsodium` from epel-testing).

Thanks for your efforts!

**Comment by carlwgeorge** [comment]
Thanks for testing @xarr, we'll promote this to the stable repos during tonight's automation.

**Comment by RonnieRocket147** [comment]
I noticed CentOS 7 has the new PHP 7.2 packages, when will CentOS 6 follow?

Thanks

**Comment by b-harper** [comment]
@RonnieRocket147,

We stopped excepting new package request for EL6 on [2017-05-11][0].

[0]: https://github.com/iuscommunity/announce/issues/5

**Comment by RonnieRocket147** [comment]
That's a shame, thanks for the info.

**Comment by carlwgeorge** [comment]
FYI, php72u has to be removed from the stable repos temporarily.  [Details can be found here](https://github.com/iuscommunity-pkg/php72u/issues/1).  We apologize for the inconvenience.

**Comment by carlwgeorge** [comment]
This package will move back to the stable repos during tonight's automation.

**Comment by i29** [comment]
pecl / pear  ?

php727-pear

**Comment by carlwgeorge** [comment]
@i29 Since pear and pecl are not compiled against a specific PHP version, a while back we switched to sharing one package for all our PHP stacks.  After you install your desired version of PHP, install the pear1 package.
