### ISSUE TITLE
php70u-pecl-lzf

### ISSUE THREAD

**Issue by rjocoleman** [iuscommunity/wishlist#165]
### What new package do you want?

php70u-pecl-lzf

### Why?

pecl-lzf is being built for php56u only, PHP 7 is supported by https://pecl.php.net/package/lzf and it would be very useful to have it available as a package for this version of php.

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by carlwgeorge** [comment]
Thanks for opening this request @rjocoleman.  This request looks like a good fit for IUS.  I will point out that [PHP 7.0 is only supported upstream for about one more year](https://secure.php.net/supported-versions.php).  Would you rather we create php71u-pecl-lzf instead?

**Comment by rjocoleman** [comment]
Thank you! I agree 7.1 would be better moving forward but unfortunately for my use case I am stuck on 7.0 for the medium term.

**Comment by carlwgeorge** [comment]
[php70u-pecl-lzf](https://github.com/iuscommunity-pkg/php70u-pecl-lzf) has been built and will move to the testing repos during tonight's automation.  Once you confirm that it works as expected, we will move it to the stable repositories.

**Comment by rjocoleman** [comment]
thank you! I will report back tomorrow after the automation has placed it in the repo.

**Comment by rjocoleman** [comment]
This is working perfectly for me from the testing repo - many thanks!

**Comment by b-harper** [comment]
@rjocoleman,

Thanks for the feedback.  We will move the packages into the stable repositories during tonight's automation run.
