### ISSUE TITLE
php72u-ioncube-loader

### ISSUE THREAD

**Issue by temporaryaccount** [iuscommunity/wishlist#166]
### What new package do you want?

php72u-ioncube-loader

### Why?

There are phpXXu-ioncube-loader packages available for other supported PHP versions.

I also hope that php72u-ioncube-loader will be readily available once php72u is released.

Thank you!

### Testing

I agree to test the new package to ensure that it works as expected.

Edited by b-harper on 2018-01-10 to change the request to php72u-ioncube-loader.

**Comment by b-harper** [comment]
Lets reopen #128 for php71u-ioncube-loader instead of creating a new issue for the same package.  We can change this one for php72u-ioncube-loader.

**Comment by b-harper** [comment]
Our php72u packages are still in testing, but an initial [spec file][0] has been created.  Packages will be hitting the testing repository during tonight's automation run.


[0]: https://github.com/iuscommunity-pkg/php72u-ioncube-loader

**Comment by xarr** [comment]
Tested.

**Stable--please promote.**

**Comment by carlwgeorge** [comment]
Thanks for testing @xarr, we'll move this to the stable repos during tonight's automation.

**Comment by carlwgeorge** [comment]
FYI, php72u and related packages have to be removed from the stable repos temporarily.  [Details can be found here](https://github.com/iuscommunity-pkg/php72u/issues/1).  We apologize for the inconvenience.

**Comment by carlwgeorge** [comment]
This package will move back to the stable repos during tonight's automation.
