### ISSUE TITLE
php 7.0.27 - minor update

### ISSUE THREAD

**Issue by futureweb** [iuscommunity/wishlist#167]
### What new package do you want?

php 7.0.27

### Why?

fixed crashes:
https://bugs.php.net/bug.php?id=75573
https://bugs.php.net/bug.php?id=75579

any info when you are ready for this minor update?

thx
Andreas Schnederle-Wagner

**Comment by carlwgeorge** [comment]
The wishlist is for new packages, not for updates to existing packages.  Issues for php70u should be opened on [its repo](https://github.com/iuscommunity-pkg/php70u/issues).  In this case, the update has [already been packaged](https://github.com/iuscommunity-pkg/php70u/commit/fdea41b0f09c657d556a597e950555c624f7db15) and has been in our [testing repositories for about a week](https://github.com/iuscommunity-pkg/php70u/releases/tag/7.0.27-1).  If you watch [that repo](https://github.com/iuscommunity-pkg/php70u) you will get notifications when we tag new releases.
