### ISSUE TITLE
php72u-pecl-zip

### ISSUE THREAD

**Issue by winnie13** [iuscommunity/wishlist#171]
### What new package do you want?

php72u-pecl-zip

### Why?

zip is a PHP essential. I need it for PHP 7.2 to run the new version of my CMS (TYPO3 9.x )

### Testing

I agree to test the new package to ensure that it works as expected.  Once I am
satisfied with the results of my testing I will comment on this issue with the
word "STABLE" to get it promoted to the stable repos.

### Hint
We may need a newer libzip5 in Epel .

### And finally...

Thank you for all your efforts--IUS rocks!

**Comment by carlwgeorge** [comment]
In the past we've shipped the zip extension as part of the -common subpackage.  [PHP 7.2.2](https://github.com/php/php-src/releases/tag/php-7.2.2) is due to be released soon, so we'll look at enabling the zip extension as part of that update.

**Comment by carlwgeorge** [comment]
I have [enabled the zip extension](https://github.com/iuscommunity-pkg/php72u/commit/196a947af535e3d8e1cf234e695e5d032ade7bb3) in the -common subpackage in our [7.2.2-1](https://github.com/iuscommunity-pkg/php72u/releases/tag/7.2.1-1) release.  It will move to the testing repos during tonight's automation.

**Comment by winnie13** [comment]
I will test on Monday

**Comment by winnie13** [comment]
Thank you !
Tested my Setup (previously ran with Remi's / Famillecollet 's  versions ).
Runs with Standard + EPEL dependencies, only. Perfect.
So for 
mod_php72u php72u-cli php72u-common php72u-devel php72u-gd php72u-intl php72u-json php72u-mbstring php72u-mysqlnd php72u-opcache php72u-pdo php72u-pdo-dblib php72u-soap php72u-xml
from 
https://dl.iuscommunity.org/pub/ius/testing/CentOS/7/x86_64/ , 7.2.2-1 ,  2.2.2018 3:17
I can say:

**Comment by winnie13** [comment]
STABLE

**Comment by carlwgeorge** [comment]
Thanks for the feedback @winnie13.  The release with the zip extension will move to the stable repos during tonight's automation.
