### ISSUE TITLE
php71u-pecl-lzf

### ISSUE THREAD

**Issue by markg314** [iuscommunity/wishlist#172]
### What new package do you want?

~~php71u-pecl-ssh2~~
php71u-pecl-lzf

### Why?

both packages are a requirement for updating a software-project from php56 (from ius-repo) to php71 (also ius-repo)
pecl-lzf is already built for php70 - the php71-build was mentioned in https://github.com/iuscommunity/wishlist/issues/165, but i am not aware of any progress there.

~~pecl-ssh2 ist currently php65-only~~

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by markg314** [comment]
just found https://github.com/iuscommunity/wishlist/issues/88

so currently it would be about php71u-pecl-lzf only.

**Comment by carlwgeorge** [comment]
[php71u-pecl-lzf](https://github.com/iuscommunity-pkg/php71u-pecl-lzf) has been built and will move to the testing repositories during tonight's automation.

FYI, we [updated our wishlist request template recently](https://github.com/iuscommunity/wishlist/pull/168), but your issue doesn't include the changes for some reason.  Once you feel the package is ready and would like to see it promoted to the stable repos, comment on the issue with the word "STABLE".

**Comment by b-harper** [comment]
Hey @markg314,

I just want to check in and see if you had a chance to test this package. Also note, this package will be moved to the development repertoires after tonight's automation run. We are making some minor changes on how we handle new package requests will be being using the development repertoires instead of the testing repertoires.

**Comment by markg314** [comment]
package installed fine. tests are still running (other departments are involved), but look good so far!

**Comment by carlwgeorge** [comment]
Happy to hear it works so far.  When you are satisfied with your own testing, let us know and we will proceed with publishing the package to the stable repos.

**Comment by b-harper** [comment]
Hey @markg314,

I am curious if you have had a chance to finish your testing.  We look forward to hearing back from you.

**Comment by markg314** [comment]
STABLE

**Comment by b-harper** [comment]
@markg314,

Thanks for the update.  These packages will get moved to the stable repositories during tonight's automation.
