### ISSUE TITLE
php72u-pecl-apcu

### ISSUE THREAD

**Issue by dvorakjan** [iuscommunity/wishlist#174]
### What new package do you want?

php72u-pecl-apcu

### Why?

APC PECL extension is already compatible with PHP 7.2.

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by dvorakjan** [comment]
Sorry, I have missed it is already in testing.

**Comment by b-harper** [comment]
Hey @dvorakjan,

Thanks for opening this request.  We built php72u-pecl-apcu as it was part of the build requirements for php72u-pecl-memcached, see #164.  If you got time to test  php72u-pecl-apcu, we would appreciate your feedback.

**Comment by carlwgeorge** [comment]
php72u and related packages have to be removed from the stable repos temporarily.  [Details can be found here](https://github.com/iuscommunity-pkg/php72u/issues/1).  We apologize for the inconvenience.

**Comment by dvorakjan** [comment]
@b-harper Hi, php72u-pecl-apcu looks STABLE in our environment. Thanks for your work.

**Comment by b-harper** [comment]
Hey @dvorakjan,

Thanks for the feedback.  See iuscommunity-pkg/php72u#1 for an update on the status of php72u packages.

**Comment by carlwgeorge** [comment]
This package will move to the stable repos during tonight's automation.
