### ISSUE TITLE
libMemcached 1.0.18

### ISSUE THREAD

**Issue by futureweb** [iuscommunity/wishlist#187]
### What new package do you want?

libMemcached 1.0.18

### Why?

as Version 1.0.18 is suggested by PHP memcached Client and Centos 7 only comes with 1.0.16

### Testing

I agree to test the new package to ensure that it works as expected.  Once I am
satisfied with the results of my testing I will comment on this issue with the
word "STABLE" to get it promoted to the stable repos.

**Comment by b-harper** [comment]
Hey @futureweb,

Please see iuscommunity-pkg/libmemcached10#1 for more information regarding this request.
