### ISSUE TITLE
parted 3.2

### ISSUE THREAD

**Issue by Nyoroon** [iuscommunity/wishlist#188]
### What new package do you want?

parted 3.2

### Why?

In parted 3.2 resizepart command was added and I miss it so much.

### Testing

I agree to test the new package to ensure that it works as expected.  Once I am
satisfied with the results of my testing I will comment on this issue with the
word "STABLE" to get it promoted to the stable repos.

**Comment by b-harper** [comment]
Hey @Nyoroon,

Thanks for taking the time to submit this issue.  Generally, IUS focuses on packages for web hosting and tend to shy away from core OS applications.  Looks like Red Hat is planning on [backporting resizepart feature to parted 3.1.90][0].


[0
