### ISSUE TITLE
python36u-libselinux

### ISSUE THREAD

**Issue by bentterp** [iuscommunity/wishlist#189]
### What new package do you want?

libselinux for the IUS packaged Python 3.6

### Why?

Other python applications like ansible need libselinux-python, so without libselinux in Python 3.6, I'm reduced to running Ansible in a Python3 flavour. But the AWS CLI behaves in mysterious ways on top of Python2 so I really want Python3. And Ansible is often used for managing ressources on AWS so I'm stuck in Python2 but needs Python3.... frustration.

### Testing

I agree to test the new package to ensure that it works as expected.  Once I am
satisfied with the results of my testing I will comment on this issue with the
word "STABLE" to get it promoted to the stable repos.

Absolutely! I can simply create a virtualenv inheriting the Python36u system packages and verify that the ansible playbook requiring selinux is working.

kind regards,
  Bent Terp

**Comment by b-harper** [comment]
Hey @bentterp,

Thanks for the request.  This will be more complicated than a standard python module as libselinux-python is a small part of the main [systemd reposiroty][0].  We will need some time to do some research and update this issue when there is additional information.

[0]: https://github.com/SELinuxProject/selinux

**Comment by bentterp** [comment]
Thank you for the fast reply. I would like to see this happen but understand that it won't happen "real soon" so I need to figure out an alternative solution for the time being. Good to know.

**Comment by bentterp** [comment]
( and I'm not trying to be passive-aggressive here, merely acknowledging the situation as it is. No criticism is intended)

**Comment by b-harper** [comment]
> No criticism is intended

None taken.

**Comment by carlwgeorge** [comment]
> without libselinux in Python 3.6, I'm reduced to running Ansible in a Python3 flavour

Do you mean python2?  And when you say "running ansible", are you referring to where you invoke ansible, or `ansible_python_interpreter` on the remote end?

If you are desiring to invoke ansible with python 3.6 (not `ansible_python_interpreter`), ansible has quite a few dependencies and IUS doesn't package any of them.  If python 3.4 is sufficient, this may be a better fit for EPEL, which has a robust python34 stack.  Also be aware that ansible's python3 support for that is only in "[tech preview](https://docs.ansible.com/ansible/latest/python_3_support.html)" status.

What does any of this have to do with the AWS CLI?  Ansible uses the boto library, not the CLI commands.

**Comment by bentterp** [comment]
Yes, that was a typo, I meant without SELInux support in Python36u then I'm forced to running Ansible on top of Python27 on the control machine (http://docs.ansible.com/ansible/latest/intro_installation.html#control-machine-requirements)

I was hoping to avoid that as the AWS CLI works best on Python3 but that might not matter in the Python27 virtualenv on the control machine used for running ansible as the virtualenv needs to be created with --system-site-packages anyways to get libselinux support. After activating the virtualenv on top of Python2.7, the AWS CLI is still running as before using Python26 so it looks to be a non-issue.
