### ISSUE TITLE
php55u update resets fpm log folder owner/group

### ISSUE THREAD

**Issue by claude-ws01** [iuscommunity/wishlist#19]
Hello,

For a long time I have been having issues with php-fpm's log file stopping being filled. Every time it is because the owner/group of the log folder has changed back to apache.

I use nginx and have unified most web server activities to a single user: nginx.

Long story short, this change of owner/group occurs when I do a yum update which includes, once a while, a php55u update.

2 points:
A. now that I'm writing about it, I realize that I could use different folder(s) name and that would most probably solve this issue.

B. on the other hand, by principle, I do not see what business has the update to change the ownership of the log folder. On an install, ok, but on an update, no.

More:
- I did look around: users home group, php-fpm config, php config... and I have not found anything that relates to "apache" user.  But I did find a lot inside the php55u.specs.

If you think I should open a ticket elsewhere, please advise me.

thx:)
Claude.

**Comment by carlgeorge** [comment]
Howdy @claude-ws01.  This repository is not used for reporting bugs, only for requesting new packages.  Please open a new issue against the php55u repo.

https://github.com/iuscommunity-pkg/php55u/issues

**Comment by claude-ws01** [comment]
thx
