### ISSUE TITLE
Openssh 7.x

### ISSUE THREAD

**Issue by netlore** [iuscommunity/wishlist#192]
### What new package do you want?

openssh 7.x (for RHEL6)

### Why?

In openssh 7.x, the "authorized keys command" feature was added (actually 6.9+ but finalised in 7.x).  This feature is available in RHEL7, but I cannot use it because any solution based on it must also work on RHEL6, since an authentication solution that works on only some machines isn't very useful!), RHEL6 only has openssh 5.3.

### Testing

I agree to test the new package to ensure that it works as expected.  Once I am
satisfied with the results of my testing I will comment on this issue with the
word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment]
RHEL 6 is in the last phase of it's [lifecycle](https://access.redhat.com/support/policy/updates/errata/#Life_Cycle_Dates) ("Maintenance Support 2", formerly known as "Production 3 Phase").  We are [no longer accepting new package requests](https://ius.io/LifeCycle/#distibution-life-cycle) for it.  Please watch the [iuscommunity/announce](https://github.com/iuscommunity/announce) repository to get notifications for announcements like [this](https://github.com/iuscommunity/announce/issues/5).
