### ISSUE TITLE
php72u-pecl-yaml

### ISSUE THREAD

**Issue by tvartom** [iuscommunity/wishlist#194]
### What new package do you want?

php72u-pecl-yaml

### Why?

Make yaml_parse() and yaml_parse_file() to work with PHP 7.2.

### Testing

I agree to test the new package to ensure that it works as expected.  Once I am
satisfied with the results of my testing I will comment on this issue with the
word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment]
Thanks for the request.  This seems like a good fit for IUS.  I've got the [spec file](https://github.com/iuscommunity-pkg/php72u-pecl-yaml) done, and builds are in progress.

**Comment by carlwgeorge** [comment]
[php72u-pecl-yaml-2.0.2-1](https://github.com/iuscommunity-pkg/php72u-pecl-yaml/releases/tag/2.0.2-1) will move to the development repos during tonight's automation.  After that you should be able to install it by running `yum --enablerepo ius-dev install php72u-pecl-yaml`.

**Comment by cervajs** [comment]
tested

LibYAML Support | enabled
-- | --
Module Version | 2.0.2
LibYAML Version | 0.1.4

STABLE

**Comment by carlwgeorge** [comment]
Thanks for testing this @cervajs.  I'll get it moved over to the stable repos.
