### ISSUE TITLE
gd 2.2.5

### ISSUE THREAD

**Issue by ChaosKid42** [iuscommunity/wishlist#195]
### What new package do you want?

gd-2.2.5 and gd-devel-2.2.5

### Why?

In recent versions of gd the function gdImageScale was added which is necessary to use ejabberd with image conversion functionality

### Testing

I agree to test the new package to ensure that it works as expected.  Once I am
satisfied with the results of my testing I will comment on this issue with the
word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment]
Thanks for opening this request.  A few early observations:

1. Stock gd is `libgd.so.2`, but the latest gd is `libgd.so.3`.  This means we can't do a replacement package, as it would break every package built against `libgd.so.2`.  A parallel package is the only sane option.
2. The end goal is to enable functionality in ejabberd, which is packaged in EPEL.  An EPEL package can't depend on an IUS package.
3. EPEL allows parallel packages.

I think considering all the factors, the best choice would be creating a gd22 package in EPEL.  I may be able to help with this, let me poke the spec file a bit and see how complicated it would be.

**Comment by carlwgeorge** [comment]
The Fedora Rawhide spec file compiles on EL7.  I don't see any blockers in getting it into EPEL.  The biggest change needed is changing the path of all files that would conflict with the stock gd packages, such as `/usr/bin/annotate` and `/usr/include/gd.h`.  The library itself is already in a different path (`/usr/lib64/libgd.so.2` vs `/usr/lib64/libgd.so.3`), so it's already partially handled.

Have you created an RPM before?  Would you like to try submitting it to EPEL?  If you do I can review the package to help with the process.

**Comment by ChaosKid42** [comment]
Thank you very much for your effort. I really appreciate that. 
I never actually created an RPM myself. I once or twice compiled one from source using a spec file already there.
What would be the next steps to take? I could at least try.
Unfortunately I won't have time until in the evening (CEST maybe 10 to 12 ours from now).

**Comment by carlwgeorge** [comment]
Closing this since it doesn't make sense for IUS.  The Fedora/EPEL community (which includes myself) should be able to provide further guidance, just not here.  I suggest reaching out over IRC in the `#epel` channel on Freenode, or perhaps the [epel-devel mailing list](https://lists.fedoraproject.org/archives/list/epel-devel@lists.fedoraproject.org/).
