### ISSUE TITLE
php56u-pecl-amqp rebuild

### ISSUE THREAD

**Issue by chasebolt** [iuscommunity/wishlist#196]
this package currently depends on `librabbitmq.so.1` which is provided by `librabbitmq-0.5.2-1.el7` from epel. epel has now released `librabbitmq-0.8.0-2.el7` which now provides `librabbitmq.so.4`. because of this broken dependency it is currently not possible to install `php56u-pecl-amqp`.

can we please get this package rebuilt?

**Comment by carlwgeorge** [comment]
This is the wrong repo to report this, please send issues for php56u-pecl-amqp to https://github.com/iuscommunity-pkg/php56u-pecl-amqp/issues.

This was already [reported](https://github.com/iuscommunity-pkg/php56u-pecl-amqp/issues/2) and has been [rebuilt](https://github.com/iuscommunity-pkg/php56u-pecl-amqp/releases/tag/1.9.3-2).  You can get the update from ius-testing now, and it will move to stable tonight.
