### ISSUE TITLE
Nextcloud 14, ffmpeg and php extension

### ISSUE THREAD

**Issue by glaringgibbon** [iuscommunity/wishlist#209]
### What new package do you want?

Nextcloud 14, ffmpeg and ffmpeg-php extension

### Why?

Apologies in advance if this sounds dumb (total CentOS n00b and almost entirely linux n00b), or if I missed something and it is already in there. Or if there is a blindingly obvious solution I'm unaware of. Etc, etc.

I have been researching installing Nextcloud 14 on CentOS 7 which requires Apache, MariaDB and PHP.

[Link to Nextcloud 14 Server Admin Manual pdf download](https://docs.nextcloud.com/server/14/Nextcloud_Server_Administration_Manual.pdf)

I am aware that this is do-able using other repositories, however, your packaging philosophy seems much better suited to stable production environments and you already have almost all of the requirements. If the above were added your repo would be a one-stop-shop and removes any dependency issues arising.

I understand if Nextcloud 14 is a step too far, but just adding ffmpeg would give you pretty much everything else in one place. The only other packages required then are (Open|Libre)Office and php mcrypt. The former is readily available while the latter appears to be deprecated in PHP 7.2 (no longer in active development). This has me stumped at the moment and I've no idea how to overcome this yet.

Finally, and once again sorry if this sounds dumb, but I went through all of the PHP modules individually to check I had everything required which was time consuming to say the least. I noticed when I installed mod_php72u it pulled in php72u-common as a dependency. So, if the answer is no to all of the above, is it possible to have a group package which pulls everything you already have together? That way, it's only one command for an install. The Nextcloud manual makes it clear that some of the PHP modules are optional. I'd rather have everything in place at the start as opposed to adding modules later if they become necessary. If this is not possible, is there a smarter way of finding the packages for Nextcloud that I haven't realised yet?

Thanks in advance for your consideration.

### Testing

I agree to test the new package to ensure that it works as expected.  Once I am
satisfied with the results of my testing I will comment on this issue with the
word "STABLE" to get it promoted to the stable repos.

**Comment by glaringgibbon** [comment]
OK, scratch the bit about mcrypt. I just had a look at one of the other issues and it appears sodium is the alternative. Is that correct?

**Comment by carlwgeorge** [comment]
> Nextcloud 14

Nextcloud is notoriously hard to package.  We've already got an [open request for NC12](https://github.com/iuscommunity/wishlist/issues/158) that we haven't been able to address.  [Fedora hasn't even figured out how to package the latest versions yet](https://bugzilla.redhat.com/show_bug.cgi?id=1433919).  I don't think this will be feasible.

> ffmpeg and ffmpeg-php extension

The goal of IUS is to provide [newer versions of base RHEL packages](https://ius.io/#ius-community-project).  FFmpeg is not part of base RHEL (or EPEL), and is thus out of scope for IUS.

> (Open|Libre)Office

IUS focuses on server software, not desktop software.

> php mcrypt

You are correct that mcrypt is deprecated in PHP 7.2.  You can read more about the state of mcrypt [on Remi's blog](https://blog.remirepo.net/post/2015/07/07/About-libmcrypt-and-php-mcrypt).  If you are using software that still requires it, I suggest using PHP 7.1 (with php71u-mcrypt) instead.

> is it possible to have a group package which pulls everything you already have together?

If you want to install every php72u package, running `yum install php72u\*` will accomplish that.  There is no value in having a meta package to do the same thing.

In the future please do not open wishlist issues for so many different things.  Limit wishlist issues to a single package request per issue.  Questions about existing packages should be filed as issues on the corresponding repository in the [iuscommunity-pkg](https://github.com/iuscommunity-pkg) organization.  If you can't find a matching repo for a package check for the SRPM name ( ex: `repoquery --source php71u-mcrypt`).

**Comment by glaringgibbon** [comment]
Hi Carl,

Thanks for your response, much obliged.

> Nextcloud is notoriously hard to package. 

I see that now. It's quite hard to install too!

> IUS focuses on server software, not desktop software.

Just to clarify, I wasn't asking for Office to be included, it's an easy install after all.

> I suggest using PHP 7.1 (with php71u-mcrypt) instead.

I had hoped to avoid 7.1 as it is approaching end of support shortly.

> If you want to install every php72u package

Not every single PHP package, just the subset that NC list in their manual. 

> In the future please do not open wishlist issues for so many different things. 

My bad, sorry. That's why I prefaced everything with a catch all apology.

> Apologies in advance if this sounds dumb (total CentOS n00b and almost entirely linux n00b), or if I missed something and it is already in there. Or if there is a blindingly obvious solution I'm unaware of. Etc, etc.

Thanks for your time. And a big thank you for the work you guys do. It's much appreciated.

**Comment by carlwgeorge** [comment]
> I had hoped to avoid 7.1 as it is approaching end of support shortly.

It's supported upstream until the end of next year ([2019-12-01](https://secure.php.net/supported-versions.php)).  I imagine by that time Nextcloud will have released a version that no longer requires mcrypt.  [This upstream issue](https://github.com/nextcloud/server/issues/8265) seems relevant, you should subscribe to it.

> It's quite hard to install too!

Since a manual install is so difficult, have you considered using the [upstream snap packages](https://docs.nextcloud.com/server/14/admin_manual/installation/source_installation.html#snaps-label)?  You can use a distribution that includes snapd such as Fedora or Ubuntu, or you can add [this repo](https://copr.fedorainfracloud.org/coprs/ngompa/snapcore-el7/) to get snapd on RHEL/CentOS 7.

> Thanks for your time. And a big thank you for the work you guys do. It's much appreciated.

You're very welcome.

**Comment by carlwgeorge** [comment]
> Are these the guys who are implementing it for NC? If so, I will.

https://github.com/nextcloud/server is the source code for Nextcloud server, and https://github.com/nextcloud/server/issues is the bugtracker.  The [Nextcloud manual](https://docs.nextcloud.com/server/14/developer_manual/bugtracker/) confirms this.

**Comment by glaringgibbon** [comment]
Cheers Carl, you're a star. I'll let you get on with stuff now. Promise.
