### ISSUE TITLE
Errata for new releases?

### ISSUE THREAD

**Issue by MarkRWatts** [iuscommunity/wishlist#214]
How feasible is it for IUS to publish updates with appropriate Errata metadata to group packages?

We import IUS into a Satellite server, and our patching is primarily based on applying Errata.
Naturally IUS packages don't get applied since they're not grouped as Errata.

It would be very useful if this were the case.

**Comment by carlwgeorge** [comment]
This is not a package request.  Please open it as an issue on [iuscommunity/infrastructure](https://github.com/iuscommunity/infrastructure).

I really wish GitHub would allow moving issues between repos.
