### ISSUE TITLE
cloud-init 18.4

### ISSUE THREAD

**Issue by arcanatigris** [iuscommunity/wishlist#217]
### What new package do you want?

cloud-init 18.4

### Why?

The cloud-init packages included in the default repos are ancient, and lack simple features like setting a password

### Testing

I agree to test the new package to ensure that it works as expected.  Once I am
satisfied with the results of my testing I will comment on this issue with the
word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment]
RHEL 7.6 has cloud-init 18.2.  That version was [tagged upstream in March of this year](https://git.launchpad.net/cloud-init/tag/?id=18.2) and includes the [ability to set passwords](https://cloudinit.readthedocs.io/en/18.2/topics/modules.html#set-passwords).

I'm guessing that you were referring to cloud-init 0.7.9 in RHEL 7.5 or CentOS, which hasn't yet released 7.6.  Update to RHEL 7.6 or wait for CentOS to finish their 7.6 rebuild.  You could also enable the [CentOS CR repository](https://wiki.centos.org/AdditionalResources/Repositories/CR) and get it now if you can't wait.
