### ISSUE TITLE
D

### ISSUE THREAD

**Issue by mcandre** [iuscommunity/wishlist#218]
### What new package do you want?

dmd-2.083.0

### Why?

To make the D programming language easier to install. Many financial applications are written in D, and could stand to benefit from the dmd compiler appearing in a basic yum repository.

### Testing

I agree to test the new package to ensure that it works as expected.  Once I am
satisfied with the results of my testing I will comment on this issue with the
word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment]
The goal of IUS is to build newer versions of packages in RHEL/CentOS.  dmd is not presently available in RHEL, and thus is eligible for the [EPEL repository](https://fedoraproject.org/wiki/EPEL), and is out of scope for IUS.

**Comment by carlwgeorge** [comment]
Fedora seems to have some support for the [D language](https://fedoraproject.org/wiki/Features/D_Programming).  The ldc compiler is packaged.  I suggest [creating a bugzilla bug](https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora%20EPEL&component=ldc&version=epel7) requesting the ldc maintainer to add an epel7 branch.
