### ISSUE TITLE
Add php56u-suhosin packages

### ISSUE THREAD

**Issue by bborysenko** [iuscommunity/wishlist#22]
Will be great to be have [php56u-suhosin](https://github.com/bborysenko/php56u-suhosin) package officially in IUS repo.

Please let me know if it requires any changes. Thanks.

**Comment by carlwgeorge** [comment]
Hello @bborysenko,

Thanks for the request.  We evaluate new package requests on a case by case basis.  This package looks like a good fit since we already have similar packages for the php55u series.  I have setup an official [repo](https://github.com/iuscommunity-pkg/php56u-suhosin) for the spec file, mainly to preserve the commit history of the php55u-suhosin package it was create from.  The only change I made was to use the prefix of `20-` instead of `02-` like you choose; the main php56u spec files has [these lines](https://github.com/iuscommunity-pkg/php56u/blob/e2f9ee38e1aa8b7f383e19240db6e97c5c68c14b/SPECS/php56u.spec#L1529-L1530):

```
        # Extensions with no dependency
        ini=20-${mod}.ini;;
```

**Comment by remicollet** [comment]
@carlwgeorge about ini name, see https://fedoraproject.org/wiki/Packaging:PHP#C_extensions_and_PECL_packages_configuration_file

So, should be 40-suhoshin.so

**Comment by carlwgeorge** [comment]
Good call @remicollet, thanks for the clarification.  I'll change it to `40-`.

**Comment by carlwgeorge** [comment]
Packages for php56u-suhosin will be added to our testing repositories during tonight's automation.  Please try them out and let us know how they work.

**Comment by bborysenko** [comment]
thanks @carlwgeorge

**Comment by bborysenko** [comment]
Maybe I have to open a new issue, but ...

Just noticed that you also have specs for [php53u-suhosin](https://github.com/iuscommunity-pkg/php53u-suhosin), but RPMs have been built only for EL5. I know that 5.3 is not maintained more, but I will be really grateful you if it can be rebuild for EL6 too and add to archive repo.

Thanks.

**Comment by carlwgeorge** [comment]
@bborysenko We did build those for EL6.

CentOS6: https://dl.iuscommunity.org/pub/ius/archive/CentOS/6/x86_64/php53u-suhosin-0.9.36-1.ius.centos6.x86_64.rpm
RHEL6: https://dl.iuscommunity.org/pub/ius/archive/Redhat/6/x86_64/php53u-suhosin-0.9.36-1.ius.el6.x86_64.rpm

I could tell you to stop using PHP 5.3, but it sounds like you already know that.

**Comment by bborysenko** [comment]
@carlwgeorge, we just need it for a few old projects that stuck with 5.3.

php56u-suhosin now in [testing](https://dl.iuscommunity.org/pub/ius/testing/CentOS/7/x86_64/php56u-suhosin-0.9.38-1.ius.centos7.x86_64.rpm), so i suppose you might close this issue.

And thanks one more time.

**Comment by carlwgeorge** [comment]
We'll leave this issue open until you confirm that the packages work as expected and we promote the packages to the stable repos.

**Comment by carlwgeorge** [comment]
@bborysenko Have you had a chance to try out the php56u-suhosin packages in testing?

**Comment by bborysenko** [comment]
@carlwgeorge sorry for delay. We have used it since last week. From our side everything working fine and there are no any issues.

**Comment by carlwgeorge** [comment]
Thanks for the feedback.  It will move to the stable repos during tonight's automation.
