### ISSUE TITLE
wforce 2.0.0 (a.k.a. weakforced)

### ISSUE THREAD

**Issue by fraenki** [iuscommunity/wishlist#221]
### What new package do you want?

wforce 2.0.0
(a.k.a. weakforced)

The project is pretty mature with the first release dating back to 2016 and the new major version 2.0.0 released only two days ago.

### Why?

wforce is an authentication policy server, which is pretty useful in combination with dovecot to block (brute-force/dictionary) attacks.

PRO: Although wforce is OSS, there are currently NO binary packages publicly available. IUS would be the primary source for RPM packages. :)

I'd suggest to build packages only for EL7.

Sources are available from:
https://github.com/PowerDNS/weakforced

Spec file:
https://github.com/PowerDNS/weakforced/blob/master/builder-support/specs/wforce.spec

Full package builder:
https://github.com/PowerDNS/pdns-builder.git

Build example:
```
$ tar xzvf v2.0.0.tar.gz
$ cd weakforced-2.0.0
$ git clone https://github.com/PowerDNS/pdns-builder.git builder
$ ./builder/build.sh -V 2.0.0 -R 1foobar -p wforce -s centos-7

$ ls -l builder/tmp/2.0.0/centos-7/dist/x86_64/*
-rw-r--r--. 1 root root   707252 Dec 13 14:31 builder/tmp/2.0.0/centos-7/dist/x86_64/wforce-2.0.0-1foobar.x86_64.rpm
-rw-r--r--. 1 root root 10071804 Dec 13 14:31 builder/tmp/2.0.0/centos-7/dist/x86_64/wforce-debuginfo-2.0.0-1foobar.x86_64.rpm
-rw-r--r--. 1 root root   472756 Dec 13 14:31 builder/tmp/2.0.0/centos-7/dist/x86_64/wforce-trackalert-2.0.0-1foobar.x86_64.rpm
```

### Testing

I agree to test the new package to ensure that it works as expected.  Once I am
satisfied with the results of my testing I will comment on this issue with the
word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment]
IUS is not a generic RPM repository.  It has the limited scope of providing newer versions of packages already in RHEL/CentOS.  Since wforce is not presently available in RHEL, it is eligible to be added to the [EPEL (Extra Packages for Enterprise Linux) repository](https://fedoraproject.org/wiki/EPEL), and is out of scope for IUS.

**Comment by carlwgeorge** [comment]
https://fedoraproject.org/wiki/EPEL/FAQ#How_do_I_get_my_packages_into_EPEL.3F
