### ISSUE TITLE
php72u for CentOS 6

### ISSUE THREAD

**Issue by temporaryaccount** [iuscommunity/wishlist#222]
### What new package do you want?

PHP 7.2 for CentOS 6

### Why?

I know of the IUS policy about not adding any new packages for the older (but still supported) distributions, but I think there should be some rare exceptions for super-popular packages like PHP.

The problem is that PHP 7.1 will be [EOL-ed](http://php.net/supported-versions.php) in December 2019, while CentOS 6 will be [EOL-ed](https://www.centosblog.com/centos-eol-dates/) in November 2020.

In case if we don't have a newer PHP version for CentOS 6 its users are going to have high security issues risks during a whole year, not getting any PHP updates fixing the discovered vulnerabilities.

### Testing

I agree to test the new package to ensure that it works as expected.  Once I am
satisfied with the results of my testing I will comment on this issue with the
word "STABLE" to get it promoted to the stable repos.

**Comment by vasillalov** [comment]
I would like to join in this request. There are many enterprise grade platforms built on PHP that now have an upgrade path to PHP 7.2. Magento is one of them but there are many others. Most vendors are now releasing patches for their platforms that enable them to run on PHP 7.2. CentOS 6 will have maintenance updates till Nov, 2020.

Remi already released 7.2 packages for RHEL6/CentOS6, however our agency relies heavily on IUS for packaging.

**Comment by carlwgeorge** [comment]
The wishlist repo exists to request new packages.  Please recreate this issue on [iuscommunity-pkg/php72u](https://github.com/iuscommunity-pkg/php72u) to discuss this.  (I see that GitHub has a beta "transfer issue" feature now, but that appears to only work within a single organization.)
