### ISSUE TITLE
vera++

### ISSUE THREAD

**Issue by mcandre** [iuscommunity/wishlist#225]
### What new package do you want?

vera++ 1.3.0

### Why?

vera++ provides checks for improving code quality in C/C++ applications.

### Testing

I agree to test the new package to ensure that it works as expected.  Once I am
satisfied with the results of my testing I will comment on this issue with the
word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment]
I don't see vera++ packaged in RHEL already.  IUS isn't a general purpose repo; it has the limited scope of provided newer versions of packages already in RHEL.  Since vera++ isn't packaged in RHEL, it's eligible to be added to EPEL instead, and is out of scope for IUS.
