### ISSUE TITLE
php71u-php-memcached

### ISSUE THREAD

**Issue by cmkl** [iuscommunity/wishlist#226]
### What new package do you want?

php71u-php-memcached

### Why?

I need this to make memcached work on the CentOS 6 server I run using php71u.

It would speed up my clients' sites noticeably and indeed would get things back to where they were before I installed  PHP 7.1 using the IUS repo.
 
### Testing

I agree to test the new package to ensure that it works as expected.  Once I am
satisfied with the results of my testing I will comment on this issue with the
word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment]
Duplicate of #111.
