### ISSUE TITLE
Add php5x-pecl-ssh2 packages

### ISSUE THREAD

**Issue by bborysenko** [iuscommunity/wishlist#23]
Hello,

Is there any chances that these packages will be added to the IUS repos? You already have official repos for them:

- [php53u-pecl-ssh2](https://github.com/iuscommunity-pkg/php53u-pecl-ssh2)
- [php54-pecl-ssh2](https://github.com/iuscommunity-pkg/php54-pecl-ssh2) and 

And this one for 5.5:
- [php55u-pecl-ssh2](https://github.com/mmckinst/php55u-pecl-ssh2)

I would appreciate you adding EL6/EL7 packages for 5.3, 5.5 and 5.6 PHP versions.

Thanks in advance!

**Comment by b-harper** [comment]
Hello @bborysenko,

Thanks for taking the time to reach out to us with this request.  The ssh2 pecl modules never made it into our stable repositories.  They were is the development repositories for awhile as a form of compromise.  See the [original request][0] and a [followup request][1] for more information. 

Personally, I have some reservations using a beta quality software (that now appears to be abandonware) to interact with an important service like SSH.  

-Ben

[0]: https://bugs.launchpad.net/ius/+bug/1170131
[1]: https://bugs.launchpad.net/ius/+bug/1271681
