### ISSUE TITLE
IUS - Centos 8

### ISSUE THREAD

**Issue by futureweb** [iuscommunity/wishlist#246]
Hey there,
as Centos 8 is released now I wanted to ask if/when IUS will be available for it?
Of course we can help with testing as used to ... ;-)
thx, bye from Austria
Andreas Schnederle-Wagner

**Comment by carlwgeorge** [comment]
I'm working on a rewrite of the IUS website, which will include an FAQ item to explain this.  This is the draft of it:

https://github.com/iusrepo/iusrepo.github.io/blob/master/markdown/faq.md#why-doesnt-ius-have-packages-for-rhel-8

I don't plan to build any EL8 IUS packages.  For example, EL8 shipped with a PHP 7.2 stream, and RHEL 8.1 Beta adds a 7.3 stream.  IUS should just no longer be necessary.  We can of course change course on this if modularity is a massive failure, but for now the plan is to just maintain IUS for the remainder of the EL6 (2020-11) and EL7 (2024-06) lifecycles.

**Comment by grzegorzzyla** [comment]
Hey,
Ok, but in IUS packages for PHP is phpxxu-interbase, which I need and I didn't find this in CentOS 8 PHP 7.2 stream. Of course I can build it out, but ... IUS just was :)

**Comment by carlwgeorge** [comment]
@grzegorzzyla The interbase subpackage is in the EL8 spec file, but disabled by a conditional.

https://git.centos.org/rpms/php/blob/c8-stream-7.2/f/SPECS/php.spec#_45

This was inheirited from the Fedora spec file.

https://src.fedoraproject.org/rpms/php/c/b4b71624e15d023ad541d47c8bf81979234efbad

If you'd like to see that enabled I suggest discussing it with Red Hat via bugzilla.

https://bugzilla.redhat.com/enter_bug.cgi?product=Red%20Hat%20Enterprise%20Linux%208&component=php

**Comment by jamieburchell** [comment]
It was easy and convenient to install PECL packages too with IUS in EL7, e.g. `php72u-pecl-memcached`, `php72u-pecl-apcu`, `php72u-pecl-imagick`

What is the EL8 way? I know ImageMagic has been replaced with GraphicsMagic.

**Comment by kovacs-andras** [comment]
While IUS is great for EVERYTHING like Apache, Git, etc. with PHP I choose Remi's repo: https://blog.remirepo.net/post/2019/09/24/CentOS-8-repository
https://rpms.remirepo.net/enterprise/8/
If you are missing ANY php module, you will find there.
If you can't find a package there, that means it's a part of an another package. :)
Regards,

**Comment by jamieburchell** [comment]
As a previous Rackspace customer I seem to remember IUS was the recommend repo and remi was frowned upon

**Comment by Paramita7** [comment]
what is the command for installing centos8 ius
following I got for centos7::
yum install -y https://centos7.iuscommunity.org/ius-...
kindly see attachment, as I got en error while I was trying to install gns3 in CentOS8.
[error.docx](https://github.com/iusrepo/wishlist/files/5300630/error.docx)

**Comment by carlwgeorge** [comment]
> what is the command for installing centos8 ius

There isn't one.  As I mentioned in [this comment](https://github.com/iusrepo/wishlist/issues/246#issuecomment-535261775), IUS doesn't build for RHEL/CentOS 8.  It's also covered in our [FAQ](https://ius.io/faq#why-doesnt-ius-have-packages-for-rhel-8).

**Comment by mastertheknife** [comment]
Hi,

I agree that having PHP 7.2, PHP 7.3 and PHP 7.4 module streams out of the box is very nice.
However we use some pecl packages such php72u-pecl-mongodb.
The advantage of such RPMs is that they get updated automatically with "yum update"

Any chance we can at least get these pecl packages for EL8?

**Comment by jamieburchell** [comment]
@mastertheknife It was marked as off-topic, but I believe @kovacs-andras comment is the answer.

As IUS have stated that there will be no CentOS 8 version and the packages we need are missing from AppStream, the next logic step short of compiling your own is to use another repository. And as Remi Collet maintains all PHP packages for RHEL, it seems the best way to go. https://pkgs.org/search/?q=php-pecl-mongodb
