### ISSUE TITLE
php73-zip

### ISSUE THREAD

**Issue by Razva** [iuscommunity/wishlist#247]
**What new package do you want?**

php73-zip

**Why?**

It's required by a lot (the majority?) of apps/software/scripts.

**Testing**

I agree to test the new package to ensure that it works as expected.  Once I am satisfied with the results of my testing I will comment on this issue with the word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment]
The zip extension is part of the common subpackage.

```
# repoquery --provides php73-common | grep zip
php-zip
php-zip(x86-64)
# repoquery --list php73-common | grep zip
/etc/php.d/20-zip.ini
/usr/lib64/php/modules/zip.so
```
