### ISSUE TITLE
php74

### ISSUE THREAD

**Issue by rossnick** [iuscommunity/wishlist#251]
**What new package do you want?**

php 7.4

**Why?**

Latest stable php release. (28 Nov 2019 release)

**Testing**

I agree to test the new package to ensure that it works as expected.  Once I am satisfied with the results of my testing I will comment on this issue with the word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment]
Hey @rossnick, thanks for the request.  I did see that PHP 7.4 was released, just haven't had the time yet to tackle it.

I was chatting with @kelnei about this in IRC, and he pointed out that this will require a newer version of libzip than is in base RHEL 7.  Additionally the PHP source no longer includes a bundled version of libzip.  To address that, I've created a libzip1 package (currently in ius-testing) that we should be able to build against.  Additionally, we need a newer version of oniguruma than is in EPEL 7, and there isn't a bundled one to use.  For various reasons, I think it would be a better solution to get the EPEL package update rather than creating an alternative version package.  I've requested that with the EPEL maintainer.

https://bugzilla.redhat.com/show_bug.cgi?id=1777660

Once the dependencies are sorted out, if anyone wants to get more involved with IUS and try to start this package, I've documented the basic process for creating an IUS package.

https://github.com/iusrepo/packaging/wiki/walkthrough

I've also documented the package guidelines for IUS (that supplement the general Fedora packaging guidelines).

https://github.com/iusrepo/packaging/wiki/guidelines

Finally, there are some notes specific to how IUS does PHP over on the php73 wiki.

https://github.com/iusrepo/php73/wiki/implementation

I'm happy to chat with anyone about this in the `#ius` channel on the Freenode IRC network.

**Comment by remicollet** [comment]
> I've created a libzip1 package 

IMHO better to use the soname in the package name (so libzip5)
(the soname have change in 1.2.0)

**Comment by kelnei** [comment]
@carlwgeorge 

I've started working on this here: https://github.com/kelnei/php74

This assumes updated libzip and oniguruma are available. I used your libzip1 from ius-testing and an oniguruma6 (6.9.4) I packaged for myself. This also uses the bundled gd and pcre. I think I ported all your php7.3 changes. Two things to note; 1) I had to update the curltls patch, as it was getting rejected during patching, and 2) I'm not sure the pdo-firebird package is correct, it was previously interbase so I did a provides for interbase. Hopefully this is a good starting point for you.

**Comment by carlwgeorge** [comment]
@remicollet

> IMHO better to use the soname in the package name (so libzip5)

That's right, I remember now that we [did that for libsodium13](https://lists.fedoraproject.org/archives/list/epel-devel@lists.fedoraproject.org/thread/PA2Y33V43KI2YOW6PAHL4YWDKP4KW2CT/#PA2Y33V43KI2YOW6PAHL4YWDKP4KW2CT).  Do you know if there has been any previous discussion around clarifying version vs soname in the [naming package guidelines](https://docs.fedoraproject.org/en-US/packaging-guidelines/Naming/#multiple)?  If not I'd like to bring it up on a mailing list.

@kelnei

> I've started working on this here: kelnei/php74

Excellent work, thanks!  Are you able to transfer that repo to the iusrepo organization?  If not I can just clone the repo and push the commits to a new remote.

> I had to update the curltls patch, as it was getting rejected during patching,

Yeah that happens from time to time.  Minor nitpick, can you rename that patch to php-7.4.0-curltls.patch?  It's customary when a patch is rebased like that to rename the file to reflect the version of the upstream software the patch was targeting.  It's not necessary on every version update, just when the upstream changes are substantial enough that the patch no longer applies and needs to be rebased.  As you can see, the previous patch was originally written for PHP 7.1.0 and continued to apply cleanly for a long time.

>  I'm not sure the pdo-firebird package is correct, it was previously interbase so I did a provides for interbase.

I saw Remi helped you get this [squared away](https://github.com/kelnei/php74/commit/36c3f519daa199aadb3bd3228212f3ab4fb909be) already.

**Comment by kelnei** [comment]
@carlwgeorge 

The patch has been renamed, and the repo has been transferred to IUS.

**Comment by carlwgeorge** [comment]
Excellent.  The only thing we're missing is the Cirrus CI config file, but there is no point in adding that until we sort out the dependencies.  I poked the [oniguruma bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1777660), which I believe is our main blocker now.

At some point I'll rename libzip1 to libzip5 as Remi suggested to match the library soname.  php74.spec also should be tweaked to build require the pkgconfig virtual provides rather than an exact name.

```diff
-BuildRequires: libzip-devel >= 0.11
+BuildRequires: pkgconfig(libzip) >= 0.11
```

Edit: I took care of the libzip build requirement [here](https://github.com/iusrepo/php74/commit/131f7828631f58107c84f3791fa5e3aff036f021) and also [sent it upstream to the Fedora spec file](https://src.fedoraproject.org/rpms/php/pull-request/3).

**Comment by jsosic** [comment]
I have rebuilt the PHP to 7.4.1 + built the following RPMs from IUS repos (with small changes):
* php74-pear-VersionControl_SVN v0.5.2
* php74-pecl-amqp v1.9.4
* php74-pecl-apcu v5.1.18
* php74-pecl-igbinary v3.0.1
* php74-pecl-memcached v3.1.4
* php74-pecl-msgpack v2.0.3
* php74-pecl-ssh2 v1.2
* php74-pecl-xdebug v2.9.0

If you want, I can publish repos and transfer them to `iusrepo` organization?

**Comment by carlwgeorge** [comment]
@jsosic Thanks for looking in to those.  How are you handling the oniguruma dependency for the main php74 package?  Once we have our main php74 package created we can look at those add on packages.

**Comment by jsosic** [comment]
I have built the onigurama6 rpm from spec file from @kelnei (available at https://github.com/kelnei/oniguruma6), and have built php74 against that RPM.

**Comment by b1rdex** [comment]
Hi guys. Sorry to bother you, but is there a way to try https://github.com/iusrepo/php74? I see there is 7.4.2 already committed, but I don't get how it can be installed.

**Comment by StanvanHoorn** [comment]
Hi Guys,
Do you have an ETA for PHP 7.4?

Thanks!

**Comment by Venorcis** [comment]
> Hi Guys,
> Do you have an ETA for PHP 7.4?
> 
> Thanks!

We're wondering the same 😁

**Comment by rossnick** [comment]
Any updates on this ?

**Comment by zanfer1** [comment]
Do you have any tentative timeline on getting PHP 7.4 into its stable? Appreciate a lot.

**Comment by davidalger** [comment]
@jsosic Any way you could publish the repos you've got for those pecl extensions? I'd like to reference a few of them as I'm building a 7.4 version of the PHP docker images building RPM files from the specs since this isn't available in IUS yet.

**Comment by jsosic** [comment]
@davidalger sure, I can publish them in one repo. How urgently do you need them? In a day or is a week fine?

**Comment by carlwgeorge** [comment]
I've initiated the process to do an incompatible upgrade of oniguruma in EPEL 7.  Once complete that should unblock us to start doing IUS builds of php74.

https://lists.fedoraproject.org/archives/list/epel-devel@lists.fedoraproject.org/thread/CNSWLDLHTWAEA6NKVI6YO3KKFP4Z2GY5/

**Comment by carlwgeorge** [comment]
php74-7.4.6-3 has been published to the ius-testing repository.  Please test it out and provide feedback here.  Be aware that you will also need to enable epel-testing to get the new oniguruma if you are installing php74-mbstring.

**Comment by rossnick** [comment]
Great news ! On my test machine, I have php73-mbstring installed. When trying to upgrade it to php74-mbstring it seems that I miss a dependency :

Error: Package: php74-mbstring-7.4.6-3.el7.ius.x86_64 (ius7-testing-x86_64)
    Requires: libonig.so.5()(64bit)

I do have epel enabled.

With google, I found a pakacge in epel-testing that seems to provide this : https://rpmfind.net/linux/RPM/epel/testing/7/x86_64/Packages/o/oniguruma-6.8.2-1.el7.x86_64.html

Should I enable epel-testing also for testing ?

**Comment by Hint-ru** [comment]
@rossnick
> Should I enable epel-testing also for testing ?

Yes. From the comment above:
> Be aware that you will also need to enable epel-testing to get the new oniguruma if you are installing php74-mbstring.

**Comment by rossnick** [comment]
As always, I read too fast. Sorry. I'll get back. I hate myself when I do that ;-)

**Comment by rossnick** [comment]
php-zip seems to have been removed from the provided features and not enabled.

I beleive commit https://github.com/iusrepo/php73/commit/1b626f01e6958a5986088a918f5c8ea843814fcf form php73 should be applied here also.

**Comment by davidalger** [comment]
> As of PHP 7.3.0, building against the bundled libzip is discouraged, but still possible by adding --without-libzip to the configuration. As of PHP 7.4.0, the bundled libzip is removed.

@rossnick PHP 7.4 no longer bundles libzip and PHP upstream dependencies on it for php packages were removed, so zip support will be moving to a php74-pecl-zip package, which I've ported and pushed into the IUS org (along with quite a number of others) and is now waiting to be published.

**Comment by rossnick** [comment]
Ok, I see. I also use amazon linux 2 with php 7.4, and "they" bundled it in php-common...

For the moment, it won't matter, I'll still be able to make some basic tests. I just had to uninstall composer, it depends on php-zip.

**Comment by remicollet** [comment]
> @rossnick PHP 7.4 no longer bundles libzip and PHP upstream

There is NO relation between bundled libzip and zip extension availability in php-src.

pecl extension make sense if you want the latest feature from the latest zip extension using the latest libzip version.

* PHP 7.4 still have zip 1.15.6 which requires libzip >= 0.11 (but 1.3.1 recommended)
* zip 1.18 take benefit of libzip 1.6 features
* zip 1.19 take benefit of libzip 1.7 features
* etc

We choose to use the pecl extension in Fedora to match libzip version available
* Fedora 32 have libzip 1.6, so zip 1.18
* Fedora 33 have libzip 1.7, so zip 1.19
* etc

**Comment by carlwgeorge** [comment]
> There is NO relation between bundled libzip and zip extension availability in php-src.

The relation is that in the past IUS choose to utilize the bundled libzip to build a zip subpackage from the main spec file, rather than maintaining a pecl extension package.  With the bundled libzip removed, we no longer have that option.

**Comment by carlwgeorge** [comment]
@rossnick (and anyone else interested) php74-pecl-zip is now available for testing along with php74.  If you're able to test it out please provide your feedback for that one in #273.

More extensions will be coming soon thanks to @davidalger.

**Comment by remicollet** [comment]
> With the bundled libzip removed, we no longer have that option.

Please explain.

* The pecl extension uses the system library
* The zip extension from main php-src uses the system library.

As soon as you have a "lilbzip5" package, you can build both.

`--with-libzip `option is removed, not the `--with-zip` one.

**Comment by rossnick** [comment]
So far, I've been able to install what we need to make one of our basic project work. So so far, so good.

But most of the more big projects needs pecl-redis https://github.com/iusrepo/wishlist/issues/258, I'll wait for that to complete my tests

**Comment by rossnick** [comment]
I've not run extensive testing of all php functions, but I haven't run in any issue with php 7.4. I'm confident enough to install this on our dev and test servers.

**Comment by carlwgeorge** [comment]
@rossnick After your testing in your dev and test environments, are you ready for this to be promoted to the main repository, i.e. production use?

**Comment by rossnick** [comment]
@carlwgeorge yes, I would be good.

**Comment by jrjohnson** [comment]
We've had no problems installing or running this and did some light user testing of our application with no issues.

**Comment by carlwgeorge** [comment]
Thanks for testing.  php74 has been promoted to the main repository.  Not all pecl extensions are complete yet, but they will addressed individually in their respective wishlist issues.

**Comment by quinncomendant** [comment]
@jsosic Is there a reason why `php74-pecl-ssh2` is not yet available in IUS? If you've successfully built the RPM, why not publish it (I'm refering to your quoted comment below)? 

I'm using `https://repo.ius.io/7/$basearch/` and was able to install php74 successfully, except for this package:
```
sudo yum install php74-pecl-ssh2
…
No package php74-pecl-ssh2 available.
```

Also see issue #298.

> I have rebuilt the PHP to 7.4.1 + built the following RPMs from IUS repos (with small changes):
> 
> * php74-pear-VersionControl_SVN v0.5.2
> * php74-pecl-amqp v1.9.4
> * php74-pecl-apcu v5.1.18
> * php74-pecl-igbinary v3.0.1
> * php74-pecl-memcached v3.1.4
> * php74-pecl-msgpack v2.0.3
> * php74-pecl-ssh2 v1.2
> * php74-pecl-xdebug v2.9.0
> 
> If you want, I can publish repos and transfer them to `iusrepo` organization?
