### ISSUE TITLE
httpd24u-mod_auth_kerb

### ISSUE THREAD

**Issue by josephcsible** [iuscommunity/wishlist#254]
**What new package do you want?**

[mod_auth_kerb](http://modauthkerb.sourceforge.net/) 5.4, built against httpd24u instead of httpd

**Why?**

There's a mod_auth_kerb package in stock CentOS to enable Kerberos authentication with Apache httpd, but it only works with the stock httpd package and not httpd24u. 

**Testing**

I agree to test the new package to ensure that it works as expected.  Once I am satisfied with the results of my testing I will comment on this issue with the word "STABLE" to get it promoted to the stable repos.

**Comment by josephcsible** [comment]
I ended up upgrading to CentOS 8 and using mod_auth_gssapi instead, so I no longer need this.

**Comment by carlwgeorge** [comment]
Thanks for following up on this @josephcsible.  Sorry I wasn't able to get to it in time to help you.

If someone else wants this in the future just comment and I'll take another look.
