### ISSUE TITLE
phpMyAdmin50

### ISSUE THREAD

**Issue by wolfy67** [iuscommunity/wishlist#255]
**What new package do you want?**
phpMyAdmin 5.0.0

**Why?**

IUS currently packages phpMyAdmin 4.9. However this version is currently supported by its developers for security fixes only.  
5.0.0 is currently the latest version available and AFAIK the requirements are more or less inline with the ones for 4.9, except for php which should be newer than 7.1 ( as opposed to php >= 5.5 for  phpMyAdmin 4.9 ).

**Testing**

I agree to test the new package to ensure that it works as expected.  Once I am satisfied with the results of my testing I will comment on this issue with the word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment]
Thanks for the suggestion @wolfy67.  I've created this package.  The source can be found at [iusrepo/phpMyAdmin50](https://github.com/iusrepo/phpMyAdmin50), and the first build `phpMyAdmin50-5.0.2-3.el7.ius` can be found in our [testing repository](https://ius.io/setup#testing).  Try it out and once you confirm it works as expected, I'll promote it to the main repository.

**Comment by wolfy67** [comment]
Thank you very much, Carl, but meanwhile I built my own package and as it is in production now I cannot test yours any more. At least not until we see an upgrade past 5.0.2...

**Comment by carlwgeorge** [comment]
@petecassetta Would you be interested in helping test this new package?

**Comment by petecassetta** [comment]
Thanks Carl, I'll take it for a spin and try to post my results by Wednesday.

**Comment by petecassetta** [comment]
It looks good to me; I tested on CentOS 7. I notice it doesn't install over phpMyAdmin49, it makes you remove 4.9, but that's OK. Uninstall of 4.9 preserves configs in .rpmsave files, so I could easily refer to them.

Seems ready to promote to release to me.

**Comment by carlwgeorge** [comment]
Ah good point, it will have file conflicts, I need to add an explicit conflict with phpMyAdmin49 like we do for other packages to make it more obvious.  Good catch!

**Comment by carlwgeorge** [comment]
Nevermind, I forgot that this is the behavior already because of the virtual provides.  phpMyAdmin49 provides `phpMyAdmin = 4.9.5-1.el7.ius`, and phpMyAdmin50 has a conflicts for `phpMyAdmin < 5.0.2-3.el7.ius`.  Everything is as expected, so this is ready to ship.  I've published it to the main repos.  Thanks again @petecassetta!
