### ISSUE TITLE
vim 8

### ISSUE THREAD

**Issue by stheine** [iuscommunity/wishlist#260]
**What new package do you want?**

vim 8.x

**Why?**

vim 8 provides enhancements over 7.x

**Testing**

I agree to test the new package to ensure that it works as expected.  Once I am satisfied with the results of my testing I will comment on this issue with the word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment]
The IUS project has reached it's end of life, and will not be addressing any more wishlist requests.

https://ius.io/faq#why-doesnt-ius-have-packages-for-rhel-8

https://github.com/iusrepo/announce/issues/41
