### ISSUE TITLE
haproxy22

### ISSUE THREAD

**Issue by olfway** [iuscommunity/wishlist#263]
**What new package do you want?**

haproxy 2.1.x

**Why?**

To quote haproxy blog:

> In HAProxy 2.1, you will see significant performance gains in key areas, exciting new features including Dynamic SSL Certificate Updates, FastCGI, and Native Protocol Tracing, and a streamlined codebase.

https://www.haproxy.com/blog/haproxy-2-1/

**Testing**

I agree to test the new package to ensure that it works as expected.  Once I am satisfied with the results of my testing I will comment on this issue with the word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment]
Upstream haproxy has adopted an even/odd cadence for their releases, with the odd numbered releases only being maintained for about a year.  See [this comment](https://github.com/iusrepo/wishlist/issues/224#issuecomment-489504523) for more details.

2.1 is only going to be maintained until early 2021.  2.2 is planned for Q2 of this year, so let's wait for that release, which will be maintained upstream until 2025.  Check out the versions chart on the [haproxy homepage](https://www.haproxy.org) for the full breakdown.

**Comment by hexa2k9** [comment]
HAProxy 2.2.0 was released on 07.07.2020

It would be super awesome to have this in the IUS Repository

**Comment by carlwgeorge** [comment]
haproxy22-2.2.1-1.el7.ius has been published to the testing repo.  Please try it out and confirm it works as expected, and then I'll promote it to the main repo.

**Comment by hexa2k9** [comment]
Thank you @carlwgeorge.

I updated one of our loadbalancer instances which is happily serving traffic at rates of 90+ Mbps running haproxy22-2.2.1-1.el7.ius.x86_64. Everything seems fine but I'll continue to monitor for a while.

**Comment by hexa2k9** [comment]
I'd say the package is stable, we haven't seen any problems ever since the update

**Comment by carlwgeorge** [comment]
I've pushed it to the main repo, enjoy!
