### ISSUE TITLE
tmux3

### ISSUE THREAD

**Issue by hemingdao** [iuscommunity/wishlist#264]
**What new package do you want?**

tmux 3.1b

**Why?**

There are bug fixes and feature improvements since 2.9

**Testing**

I agree to test the new package to ensure that it works as expected.  Once I am satisfied with the results of my testing I will comment on this issue with the word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment]
Thanks for the suggestion.  I've created a [tmux3](https://github.com/iusrepo/tmux3) package.  The initial release tmux3-3.1-3.el7.ius is available in the ius-testing repository for your evaluation.  If it works as expected I'll promote it to the main repository.

**Comment by carlwgeorge** [comment]
I'm removing this package from the testing repos due to lack of feedback.

**Comment by cuviper** [comment]
@carlwgeorge If you're willing to reinstate this, I'd be happy to test and give feedback.
