### ISSUE TITLE
httpd 2.4.43

### ISSUE THREAD

**Issue by lidiexy** [iuscommunity/wishlist#265]
**What new package do you want?**
httpd-2.4.43

**Why?**
Security Issues in the current 2.4.41.

**Testing**
I agree to test the new package to ensure that it works as expected.  Once I am satisfied with the results of my testing I will comment on this issue with the word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment]
[This wishlist is used to request new packages for the IUS repository.  If you need to report an issue or request an update for an existing package, file an issue on that repository, not here.](https://github.com/iusrepo/wishlist/blob/master/.github/contributing.md)

https://github.com/iusrepo/httpd24u/issues

**Comment by lidiexy** [comment]
Thanks, I'll do.
