### ISSUE TITLE
php73-pecl-ssh2

### ISSUE THREAD

**Issue by kkavchakHT** [iuscommunity/wishlist#266]
**What new package do you want?**

php73-pecl-ssh2

**Why?**

We currently php73-php-pecl-ssh2 package from another repo as we have moved to php 7.3 with code that was originally written for php 5.6. 

It would be preferred if we had the package available in the IUS repo, as we are using that for php 7.3. 

**Testing**

I agree to test the new package to ensure that it works as expected.  Once I am satisfied with the results of my testing I will comment on this issue with the word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment]
Thanks for opening this request.  I've created [php73-pecl-ssh2](https://github.com/iusrepo/php73-pecl-ssh2) and published php73-pecl-ssh2-1.2-5.el7.ius to the testing repo.  Please try it out and let me know if it works as expected.

**Comment by JustJohnAlcock** [comment]
@carlwgeorge I have just tested the following functions with no errors on a CentOS 7 64bit server running PHP 7.3
ssh2_connect
ssh2_auth_password
ssh2_sftp - upload, download and delete

All worked as expected. PHP 7.4 next?

**Comment by carlwgeorge** [comment]
Thanks for testing @Justjohn1982.  I've promoted this package to the main repo.  Please open a new issue to request php74-pecl-ssh2.
