### ISSUE TITLE
Git Package for the latest version

### ISSUE THREAD

**Issue by mervin-john** [iuscommunity/wishlist#267]
**What new package do you want?**

Git Latest Version so as to use the git in Solaris
https://git-scm.com/download/linux

**Why?**

We cannot install the Git as mentioned in website as we have limited access to internet

**Testing**

I agree to test the new package to ensure that it works as expected.  Once I am satisfied with the results of my testing I will comment on this issue with the word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment]
[IUS is a yum repository that provides newer versions of select software for RHEL and CentOS.](https://ius.io)  We don't build Solaris packages.

**Comment by mervin-john** [comment]
Hi Carl,

If you can build linux package(tar.gz) should do great.
Is it possible?

**Comment by carlwgeorge** [comment]
No, IUS only builds RPM packages for RHEL and CentOS.  We're not a generic packaging service for the git project.
