### ISSUE TITLE
Git 2.18

### ISSUE THREAD

**Issue by mddvul22** [iuscommunity/wishlist#268]
**What new package do you want?**

Git 2.18.3

**Why?**

Git 2.18 is the version of Git supplied in RHEL/Centos 8. Packaging Git 2.18 for RHEL/Centos 7 would be beneficial for us, and other organizations that wish to maintain a single version of git across all of their servers, regardless of the version of RHEL/Centos they are running.

**Testing**

I agree to test the new package to ensure that it works as expected.  Once I am satisfied with the results of my testing I will comment on this issue with the word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment]
IUS already ships [git222](https://github.com/iusrepo/git222), and we have a new [git224](https://github.com/iusrepo/wishlist/issues/253) in testing that is pending user feedback.  Would either those suit your needs?  I know that they aren't the identical version to what is in EL8, but I don't see how that matters.  What's more important is that the desired features exist, and 2.22 and 2.24 have all the features that are present in 2.18 (and then some).  This would allow you to use all the same features that are present in EL8 stock git on EL7.

If you do happen to try git224 and it works for you, please provide feedback in the [request](https://github.com/iusrepo/wishlist/issues/253).  The original requestor disappeared and IUS requires a user (any user, doesn't have to be the original requestor) to confirm a package works as expected before promoting it to the main repo.

**Comment by mddvul22** [comment]
Not sure.  If we can't find any source for 2.18 RPMs, we might try them.  I can appreciate that both versions have all of the features of 2.18.  But in our environment, we would prefer to be able to have the same code base across both RHEL 7/8.

**Comment by carlwgeorge** [comment]
If you can provide an example of code that works in 2.18 that doesn't work in 2.22 or 2.24, I'd love to hear about it.  As far as I've seen git has excellent backwards compatibility, and reserves removing functionality for major version bumps.

If you absolutely positively want to ensure the exact same version (including patches), your only choice is to rebuild the EL8 SRPM on EL7.  That's not the goal for IUS, so you'd be on your own there.

**Comment by mddvul22** [comment]
OK, thanks.
