### ISSUE TITLE
Python 3.8

### ISSUE THREAD

**Issue by vgiralt** [iuscommunity/wishlist#269]
**What new package do you want?**

python 3.8

**Why?**

We are running PCR  testing robots that require Python 3.8 for defining the test recipes and we are a CentOS shop. Having the latest version of Python will be beneficial to the whole CentOS community.

**Testing**

I agree to test the new package to ensure that it works as expected.  Once I am satisfied with the results of my testing I will comment on this issue with the word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment]
See https://github.com/iusrepo/packaging/issues/7.  Python 3.8 is eligible for EPEL and thus out of scope for IUS.

**Comment by jnewbigin** [comment]
Python 3.8 is now available from software collections testing repo https://centos.pkgs.org/7/centos-sclo-rh-testing-x86_64/rh-python38-python-3.8.0-15.el7.x86_64.rpm.html
