### ISSUE TITLE
php74-pecl-yaml

### ISSUE THREAD

**Issue by jgupta** [iuscommunity/wishlist#282]
php74-pecl-yaml

**Why?**

YAML is a common configuration file for many popular projects. Without YAML support the IUS PHP 7.4 package has limited use for many applications I use and write. Please can we include it?

Currently available as php73-pecl-yaml and php72u-pecl-yaml

I agree to test the new package to ensure that it works as expected. Once I am
satisfied with the results of my testing I will comment on this issue with the
word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment]
Thanks for opening this request.  I've created [php74-pecl-yaml](https://github.com/iusrepo/php74-pecl-yaml) and published php74-pecl-yaml-2.1.0-3.el7.ius to the testing repo.  Please try it out and let me know if it works as expected.

**Comment by zrice57** [comment]
STABLE

**Comment by zrice57** [comment]
I tested this and it's working as expected.

**Comment by jeffsheltren** [comment]
Thanks @zrice57 -- I pushed php74-pecl-yaml-2.1.0-3.el7.ius to the main repo.
