### ISSUE TITLE
imagick and geoip extension is available until php7.3 only

### ISSUE THREAD

**Issue by sumitgarg44** [iuscommunity/wishlist#283]
I see geoip and imagick extension is not added for php7.4.

Can it be added?

    # yum list php*magi*
Available Packages
php-magickwand.x86_64                                                                                          1.0.9-7.el7                                                                                     epel
php-pecl-gmagick.x86_64                                                                                        1.1.7-0.2.RC2.el7                                                                               epel
php-pecl-imagick.x86_64                                                                                        3.4.4-1.el7                                                                                     epel
php72u-pecl-imagick.x86_64                                                                                     3.4.4-1.el7.ius                                                                                 ius
php72u-pecl-imagick-devel.x86_64                                                                               3.4.4-1.el7.ius                                                                                 ius
php73-pecl-imagick.x86_64                                                                                      3.4.4-3.el7.ius                                                                                 ius
php73-pecl-imagick-devel.x86_64                                                                                3.4.4-3.el7.ius                                                                                 ius

**Comment by carlwgeorge** [comment]
php74-pecl-imagick-3.4.4-4.el7 is already available in the testing repo.  Please try it out and provide your feedback in issue #278.

No one has asked for php74-pecl-geoip yet.  Please follow the [instructions](https://github.com/iusrepo/wishlist/blob/master/.github/contributing.md) and template for requesting a new package.
