### ISSUE TITLE
mod_limitipconn

### ISSUE THREAD

**Issue by rajcz** [iuscommunity/wishlist#289]
Please can you add this to repo? https://dominia.org/djao/limitipconn2.html

It is lighweihght and simple solution for limit connection from one IP to virtual host or directory. 

In epel is version, which has dependecies on base OS httpd. 

Thank you.

Testing

I agree to test the new package to ensure that it works as expected. Once I am satisfied with the results of my testing I will comment on this issue with the word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment]
The IUS project has reached it's end of life, and will not be addressing any more wishlist requests.

https://ius.io/faq#why-doesnt-ius-have-packages-for-rhel-8

https://github.com/iusrepo/announce/issues/41
