### ISSUE TITLE
php74-pecl-geoip

### ISSUE THREAD

**Issue by Bllacky** [iuscommunity/wishlist#292]
For many web servers, it is necessary to have php74-pecl-geoip. Currently, this package is missing.
If this package is added then I can finally move to PHP74 using IUS repo.

Thank you!

**Comment by logisquebec** [comment]
Hello. Same problem here.
Thank you

**Comment by carlwgeorge** [comment]
The IUS project has reached it's end of life, and will not be addressing any more wishlist requests.

https://ius.io/faq#why-doesnt-ius-have-packages-for-rhel-8

https://github.com/iusrepo/announce/issues/41
