### ISSUE TITLE
mariadb105

### ISSUE THREAD

**Issue by gergnz** [iuscommunity/wishlist#296]
**What new package do you want?**

mariadb105

**Why?**

Several InnoDB improvements can be found in 10.5:
https://mariadb.com/kb/en/changes-improvements-in-mariadb-105/

**Testing**

I agree to test the new package to ensure that it works as expected.  Once I am satisfied with the results of my testing I will comment on this issue with the word "STABLE" to get it promoted to the stable repos.

**Comment by fthommen** [comment]
I'd be interested in mariadb105 (specifically MariaDB >= 10.5.2) for the same reasons as mentioned by @gergnz. Most specifically we are interested in the fact, that [MariaDB 10.5.2 has dropped the `INNODB_TABLESPACES_SCRUBBING` tables in Mariadb 10.5.2](https://mariadb.com/kb/en/mariadb-1052-release-notes/). These tables are creating problems when dumping databases using an unprivileged backup user.

**Comment by carlwgeorge** [comment]
The IUS project has reached it's end of life, and will not be addressing any more wishlist requests.

https://ius.io/faq#why-doesnt-ius-have-packages-for-rhel-8

https://github.com/iusrepo/announce/issues/41
