### ISSUE TITLE
php74-pecl-ssh2

### ISSUE THREAD

**Issue by JustJohnAlcock** [iuscommunity/wishlist#298]
Can you please add the PECL SSH2 package to PHP 7.4

php74-pecl-ssh2

This package not being present is preventing me updating to PHP7.4

I agree to test the new package to ensure that it works as expected.  Once I am satisfied with the results of my testing I will comment on this issue with the word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment]
The IUS project has reached it's end of life, and will not be addressing any more wishlist requests.

https://ius.io/faq#why-doesnt-ius-have-packages-for-rhel-8

https://github.com/iusrepo/announce/issues/41
