### ISSUE TITLE
git 2.30.2

### ISSUE THREAD

**Issue by dexxtreme** [iuscommunity/wishlist#299]
**What new package do you want?**

git 2.30.2 / git230

**Why?**

A newly announced security vulnerability affects all versions of git between 2.15 and 2.30.2 => https://github.blog/2021-03-09-git-clone-vulnerability-announced/

**Testing**

I agree to test the new package to ensure that it works as expected.  Once I am satisfied with the results of my testing I will comment on this issue with the word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment]
Hey @dexxtreme!  The git project also [backported](https://lore.kernel.org/git/xmqqim6019yd.fsf@gitster.c.googlers.com/) the fix to multiple earlier versions, including 2.22.5 and 2.24.4.  Our [git222](https://github.com/iusrepo/git222/pull/10) and [git224](https://github.com/iusrepo/git224/pull/7) packages have been updated to the relevant versions.  Packages are available in ius-testing.

There is still demand for a newer git package for other reasons, but we can track that over in #297.
