### ISSUE TITLE
Add Mongo to the PHP 5.6 Repo

### ISSUE THREAD

**Issue by Rewt0r** [iuscommunity/wishlist#3]
Seeing as this is included on previous version of PHP could you also please include this for the PHP 5.6 branch?

**Comment by b-harper** [comment]
Hey Rewt0r,

Thanks for the emails and submitting this issue.  Over email, we discussed that this package would be a good fit for IUS and you are willing to test the package before it get pushed to the stable repos.

Yesterday, I got some initial packages built and pushed into the testing repos.  I just discovered that I forgot to include RHEL 6 and those will get pushed to the testing repos during tonight's automation run.  

Please let us know when you have had a chance to test this package.  

-ben

**Comment by Rewt0r** [comment]
Hi Ben,

Apologies I forgot to include that we use RHEL7.

Regards

**Comment by b-harper** [comment]
The RHEL 7 packages are already in the testing repos.  

Also, the follow is the repo for the package configuration:

https://github.com/iuscommunity-pkg/php56u-pecl-mongo

**Comment by Rewt0r** [comment]
Seems to be working fine here:

>mongo

>MongoDB Support	enabled
Version	1.6.0
Streams Support	enabled
SSL Support	enabled
Supported Authentication Mechanisms
MONGODB-CR	enabled
SCRAM-SHA-1	enabled
MONGODB-X509	enabled
GSSAPI (Kerberos)	enabled
PLAIN	enabled

**Comment by b-harper** [comment]
Thanks for the feedback.  This package will hit the stable repos tomorrow.

-Ben
