### ISSUE TITLE
php74-pecl-smbclient

### ISSUE THREAD

**Issue by jpmv27** [iuscommunity/wishlist#300]
**What new package do you want?**

php74-pecl-smbclient

**Why?**

Required by NextCloud for support of SMB as external storage.
php73-pecl-smbclient exists, would like to upgrade from PHP 7.3 to 7.4.

**Testing**

I agree to test the new package to ensure that it works as expected.  Once I am satisfied with the results of my testing I will comment on this issue with the word "STABLE" to get it promoted to the stable repos.

**Comment by greinick** [comment]
I'll second that!

**Comment by carlwgeorge** [comment]
The IUS project has reached it's end of life, and will not be addressing any more wishlist requests.

https://ius.io/faq#why-doesnt-ius-have-packages-for-rhel-8

https://github.com/iusrepo/announce/issues/41
