### ISSUE TITLE
lua53u-luaossl

### ISSUE THREAD

**Issue by lastmikoi** [iuscommunity/wishlist#301]
**What new package do you want?**

lua-luaossl 20190731 or newer, built for lua53u

**Why?**

In IUS-provided HAProxy 2.2, one might want to use lua-luaossl, however the only available version is compiled against Lua 5.1 and doesn't seem to be usable with haproxy22.

My specific use-case is to deploy https://github.com/haproxytech/haproxy-lua-acme for managing my LetsEncrypt certificate straight into HAProxy, without certbot or other rather intrusive tools.

**Testing**

I agree to test the new package to ensure that it works as expected.  Once I am satisfied with the results of my testing I will comment on this issue with the word "STABLE" to get it promoted to the stable repos.

**Early footwork**

I've managed to get a custom built package working by applying the following patch against https://download-ib01.fedoraproject.org/pub/epel/7/SRPMS/Packages/l/lua-luaossl-20190731-1.el7.src.rpm:
```
--- lua-luaossl.spec.orig	2021-04-07 21:07:17.393712673 +0200
+++ lua-luaossl.spec	2021-04-07 21:16:52.425803375 +0200
@@ -1,21 +1,21 @@
-%{!?luaver: %global luaver %(lua -e "print(string.sub(_VERSION, 5))" || echo 0)}
+%{!?luaver: %global luaver %(lua-5.3 -e "print(string.sub(_VERSION, 5))" || echo 0)}
 %global lualibdir %{_libdir}/lua/%{luaver}
 %global luapkgdir %{_datadir}/lua/%{luaver}
 
-%global luacompatver 5.1
+%global luacompatver 5.3
 %global luacompatlibdir %{_libdir}/lua/%{luacompatver}
 %global luacompatpkgdir %{_datadir}/lua/%{luacompatver}
 
 %global luapkgname luaossl
 
-Name:           lua-%{luapkgname}
+Name:           lua53u-%{luapkgname}
 Version:        20190731
-Release:        1%{?dist}
+Release:        2%{?dist}
 Summary:        Most comprehensive OpenSSL module in the Lua universe
 
 License:        MIT
 URL:            https://github.com/wahern/%{luapkgname}
-Source0:        https://github.com/wahern/%{luapkgname}/archive/rel-%{version}/%{name}-%{version}.tar.gz
+Source0:        https://github.com/wahern/%{luapkgname}/archive/rel-%{version}/lua-%{luapkgname}-%{version}.tar.gz
 
 %if 0%{?fedora}
 Patch1:         0001-openssl-in-fedora-has-patches-for-EPV_KDF.patch
@@ -24,8 +24,8 @@
 BuildRequires:  gcc
 BuildRequires:  make
 BuildRequires:  openssl-devel
-BuildRequires:  lua
-BuildRequires:  lua-devel
+BuildRequires:  lua53u
+BuildRequires:  lua53u-devel
 
 %if 0%{?fedora} || 0%{?rhel} > 7
 BuildRequires:  compat-lua
```

However I am yet to test it thoroughly and I've taken a quick-and-dirty approach. I'd gladly defer to a more experienced packager.

**Comment by carlwgeorge** [comment]
The IUS project has reached it's end of life, and will not be addressing any more wishlist requests.

https://ius.io/faq#why-doesnt-ius-have-packages-for-rhel-8

https://github.com/iusrepo/announce/issues/41
