### ISSUE TITLE
Git 2.31.1

### ISSUE THREAD

**Issue by Legends0** [iuscommunity/wishlist#302]
**What new package do you want?**

git 2.31.1

**Why?**

Need access to new features since Git 2.30.0. Atlassian products are going to soon require at least Git 2.30.0. Example from Bitbucket:
WARN  [main]  c.a.s.i.s.g.b.DefaultGitBinaryHelper /bin/git is version 2.24.3. The next major Bitbucket version will require Git 2.30.0 or higher.

**Testing**

I agree to test the new package to ensure that it works as expected.  Once I am satisfied with the results of my testing I will comment on this issue with the word "STABLE" to get it promoted to the stable repos.

**Comment by Legends0** [comment]
Related #297, #299

**Comment by Legends0** [comment]
As of bitbucket server 7.13.0, this warning exists:
`WARN  [main]  c.a.s.i.s.g.b.DefaultGitBinaryHelper /bin/git is version 2.24.4. The next major Bitbucket version will require Git 2.30.0 or higher.`

**Comment by Legends0** [comment]
Bitbucket 7.14.0 now [supports Git 2.32](https://jira.atlassian.com/browse/BSERV-12890?src=confmacro)

Also, there is a related issue on the IUS git-224 repository:  iusrepo/git224#9

**Comment by nkadel** [comment]
I've already done almost all the work for you, see https://github.com/nkadel/nkadel-git232-srpm for git 2.32.
Legends0, would you be willing to give that a spin?

**Comment by bhundven** [comment]
Newer versions of gitlab (14.4.0) require git >= 2.33.x. Anyway we can bump this request to 2.33.1?

**Comment by AmandaAtBBC** [comment]
[Renovate](https://github.com/renovatebot/renovate/blob/main/docs/usage/getting-started/running.md#npm-package-cli) also requires git >= 2.33.0.  Please can we bump this request to 2.33.  (or should I raise a separate Wishlist Issue?)

**Comment by panglin** [comment]
Can we make this git >= 2.35.2, please?  There's a vulnerability in older versions.
https://github.blog/2022-04-12-git-security-vulnerability-announced/

**Comment by Jackenmen** [comment]
In 2 weeks, git222 and git224 packages will be removed from the main IUS repo (at which point they will be moved to the archive repository) and there will no longer be any git packages in the IUS repository:
https://github.com/iusrepo/announce/issues/35

I subscribe to the iusrepo/announce repository for this reason but I wasn't taking any action sooner because I assumed that I will only need to change the package I use to a newer one but it seems like in 2 weeks there will be no git packages at all :/

**Comment by carlwgeorge** [comment]
Closing in favor of #310.
