### ISSUE TITLE
Centos 6 - Let's Encrypt X3 Cert expiration Problem

### ISSUE THREAD

**Issue by futureweb** [iuscommunity/wishlist#307]
Hi @carlwgeorge,
I know Centos 6 IUS is "dead" as C6 is EOL but maybe you could still give a helping hand to those who are affected by the X3 CA Cert Expiration of Let's Encrypt Certs.
As you can see here (and on other Boards) - https://community.letsencrypt.org/t/rhel-centos-6-openssl-client-compatibility-after-dst-root-ca-x3-expiration - there are lot's of Server Admins  who struggle with this Problem.
Just trying to reach out if you maybe could give a helping hand on this? ;-)
thx, bye from Austria
Andy

**Comment by carlwgeorge** [comment]
I have no interest in enabling people to keep using an EOL operating system.  That's also completely out of scope for IUS.
