### ISSUE TITLE
phpMyAdmin 5.1.x

### ISSUE THREAD

**Issue by jbartak** [iuscommunity/wishlist#308]
**What new package do you want?**

phpMyAdmin `5.1.x`

**Why?**

- PMA `5.1.3` is currently latest LTS version.
- PMA `5.1.4` will probably fix the bug from https://github.com/phpmyadmin/phpmyadmin/issues/17434.

**Testing**

I agree to test the new package to ensure that it works as expected.  Once I am satisfied with the results of my testing I will comment on this issue with the word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment]
The IUS project has reached it's end of life, and will not be addressing any more wishlist requests.

https://ius.io/faq#why-doesnt-ius-have-packages-for-rhel-8

https://github.com/iusrepo/announce/issues/41
