### ISSUE TITLE
Centos 7 --> RHEL 8 derivative --> ELevate

### ISSUE THREAD

**Issue by futureweb** [iuscommunity/wishlist#309]
Hello everyone,

you all probably already know about AlmaLinux's ELevate project, don't you?
The project works pretty well to upgrade simple Centos 7 installations to a current RHEL 8 derivative such as AlmaLinux, CentOS Stream, Oracle or Rocky Linux ...

Unfortunately, it does not (yet) support installations that use IUS.
Maybe you are interested in making the ELevate project compatible with IUS?
That would probably bring quite a lot of added value to many of Admins which rely on your Packages! :-)

https://wiki.almalinux.org/elevate/Contribution-guide.html

Hope you consider this idea as valueable enough to take a look into this 👍 

best regards from Austria
Andy

**Comment by carlwgeorge** [comment]
This repo is for package requests in IUS.  This suggestion is completely off topic.

IUS doesn't offer EL8 packages, so I have no idea how someone would map out the conversion from IUS EL7 packages to stock EL8 packages or EL8 modular packages.  I wish anyone attempting this luck.
