### ISSUE TITLE
Git 2.36

### ISSUE THREAD

**Issue by panglin** [iuscommunity/wishlist#310]
**What new package do you want?**

git 2.36.0

**Why?**

Previous versions have security vulnerabilities as detailed here:
https://github.blog/2022-04-12-git-security-vulnerability-announced/
https://lore.kernel.org/git/xmqqv8veb5i6.fsf@gitster.g/

**Testing**

I agree to test the new package to ensure that it works as expected.  Once I am satisfied with the results of my testing I will comment on this issue with the word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment]
I've created [git236](https://github.com/iusrepo/git236).  It's available in the testing repository.  Try it out and let me know if it works correctly.

**Comment by Jackenmen** [comment]
> Try it out and let me know if it works correctly.

In my testing, the package seems to work correctly. Other than just running a few of the regular commands, I ran git's test suite and some of my own git-related tests as well and they all seem to work fine.

**Comment by panglin** [comment]
Testing on CentOS 7.9 x86_64 VirtualBox. RPM install/uninstall run cleanly. I tested some basic commands with github repos (clone, diff, push, pull, fetch).

**Comment by carlwgeorge** [comment]
Thanks for the testing feedback.  I've promoted git236-2.36.1-2.el7.ius to the main repo.
