### ISSUE TITLE
php70u-pecl-xdebug

### ISSUE THREAD

**Issue by ckortekaas** [iuscommunity/wishlist#33]
Firstly, thanks for updating most php packages to php7!

XDebug 2.4 (currently at RC3) supports PHP7. XDebug is a must have for many PHP developers. IUS supported this for php56u-pecl-xdebug.

I'm happy to test (and perhaps contribute).

**Comment by ckortekaas** [comment]
BTW, I'm currently using a workaround by compiling xdebug in, as can be seen here:
https://github.com/uqlibrary/docker-fpm70/blob/master/Dockerfile#L36

**Comment by Xon** [comment]
IUS = Inline with Upstream Stable. 
I don't expect IUS php7 xdebug support until a stable release is out.

**Comment by ckortekaas** [comment]
Fair enough, though xdebug is the type of thing you would never have enabled in a production environment where you need 'stable'. It's for development environments where stability isn't so important. That said - good point, and if it needs to wait for a stable xdebug 2.4, hopefully it won't be too long.

**Comment by Xon** [comment]
Speaking as a developer who has used buggy debugging tools, having stable tools can be quite a bit less stressful.

**Comment by carlwgeorge** [comment]
Howdy @ckortekaas,

Thanks for the request.  We evaluate new package requests on a case-by-case basis.  Here is our basic evaluation criteria.

1. Is the new package a good fit for IUS?
2. Is the new package maintainable with our current resources?
3. Is the requester willing to test the new package to ensure it works as expected?

The package is a good fit, as you noted that we have packaged it for prior PHP versions.  But as @Xon noted, we have a strong preference to wait until there is a stable release that supports PHP 7.  When it does, it should be maintainable and you have agreed to help test, so our criteria is met.

**Comment by carlwgeorge** [comment]
Xdebug 2.4.0 stable has [been released](https://pecl.php.net/package-changelog.php?package=xdebug&release=2.4.0), with support for PHP7.  I'll get started on the spec file for our version of the package.

**Comment by carlwgeorge** [comment]
This package has been completed and will move to our testing repositories during tonight's automation.  Let us know when you have tested it @ckortekaas.

**Comment by Xon** [comment]
:+1:

**Comment by ckortekaas** [comment]
Thanks @carlwgeorge. I've started testing it out (see https://github.com/uqlibrary/docker-fpm70/commit/6279ae7a8b41b6ba217e8e62fd31c6d1c8116b14) and will put it through it's paces tomorrow. So far it's looking good.

**Comment by ckortekaas** [comment]
Hi @carlwgeorge - I've been trying it out in PHPStorm and it all works well. Works as expected!

**Comment by carlwgeorge** [comment]
Thanks, glad to hear it.  It will move to the stable repos during tonight's automation.  Thanks for participating in IUS!
