### ISSUE TITLE
Xdebug for PHP 5.6

### ISSUE THREAD

**Issue by hugoboos** [iuscommunity/wishlist#4]
In order to debug in PHP 5.6 we need xdebug support. Also xdebug helps us to generate code converage reports.
It would be nice to have a xdebug package available.

I'm willing to help with the development of the package.

**Comment by cgtx** [comment]
Thanks for opening a request Hugo.  I feel that this package is a good fit for IUS, and should be maintainable.  We will work on getting an initial rpm put together.

**Comment by b-harper** [comment]
Hey hugoboos,

Initial packages have been built and will hit the testing repos tomorrow.  Please let us know if they work for your use case.

-Ben

**Comment by hugoboos** [comment]
Thanks, we are going to test them out.

**Comment by hugoboos** [comment]
Just tested with two of our projects. Everything seems to be working. Thanks!

Are you planning to update Xdebug to the latest upstream?

**Comment by cgtx** [comment]
Thanks for the feedback @hugoboos.  I'll move the existing version to the stable repo, and start work getting it updated to the latest upstream (2.3.2).

**Comment by cgtx** [comment]
This package is updated.  `php56u-pecl-xdebug-2.3.2-1.ius` will move to our testing repos tonight.  At this point we can close this request, and the package will follow our normal processes, i.e. new releases stay in testing for about two weeks before moving to stable.

**Comment by cgtx** [comment]
`php56u-pecl-xdebug-2.3.2-1.ius` will move to our stable repos tonight.
