### ISSUE TITLE
php55u packages for CentOS7 ?

### ISSUE THREAD

**Issue by jonathanvaughn** [iuscommunity/wishlist#40]
Is there a reason for not having 5.5? I know it's going to EOL "soon" but I figured it wasn't EOL yet, so expected to find it.

We're moving our dockerized based PHP development system from CentOS 6 to 7 because of limitations in libcurl (need 7.2+ for TLS 1.2 to be enabled by default, which is needed for example to talk to PayPal and similar APIs). 

It's not the end of the world but it means rebuilding the docker images will take longer since I'll have to figure out an equivalent set of ./configure options for the packages we normally use and build it all from source.

**Comment by carlwgeorge** [comment]
IUS typically builds packages only after they are requested.  When EL7 first came out, we knew that PHP, MariaDB, and Python would be requested right away, so we went ahead and preemptively built those.  We did not build every version, just the most recent ones at the time, so that we would be able to offer at least one newer version than stock.

There is nothing technical that is blocking us from porting php55u to EL7, but as you pointed out, the 5.5 branch will be EOL in about [5 months](http://php.net/supported-versions.php) (2016-07-10).  This is a factor in whether we take this on or not.  We would like to help you avoid custom compiling yourself if possible.  I have been asked about this before, and the conversation always ended up with the user being OK with using php56u instead.  Is there a compatibility issue in your use case that is preventing you from using the available 5.6 packages?  Also, it is worth mentioning that EL7 stock php is 5.4, which is sufficient for some users.

**Comment by jonathanvaughn** [comment]
We do PHP development work for various clients whose production environments encompass everything from PHP 5.3 to 5.6, with now and then the occasional 5.2 just to make things interesting. At some point we'll be supporting PHP 7.0 too, but haven't run into any clients on it yet.

While we'd like to be able to just have everyone run the latest & greatest, the minefield of various extensions written by various other developers over the years, of varying quality and compatibility, often prevents upgrading. While we could spend time to update some of those to work in newer versions, it is time our clients don't want to pay for, and some extensions are encrypted so we can't easily modify them anyways. Add to this their various shared hosting environments where we either can't control the PHP versions provided or the choices aren't inclusive of the latest versions, and we have to be able to work with all versions of PHP. :)

And even in the case where a particular project runs fine under 5.6, if the production environment is 5.5 we want our development environment to be 5.5 too so that we can rule out any problems due to differing environments.

**Comment by carlwgeorge** [comment]
We have decided to move forward with bringing php55u to EL7.  Work is in progress to get these packages completed.

**Comment by carlwgeorge** [comment]
The base set of php55u packages are now in the EL7 testing repositories.  That includes php55u (and all it's subpackages), php55u-pear, and php55u-pecl-jsonc.  We are still working on the remaining php55u modules.

**Comment by jonathanvaughn** [comment]
Ran a test and at the moment, the only things missing so far from ius-testing (that we use) are:
```
No package php55u-pecl-igbinary available.
No package php55u-pecl-memcache available.
No package php55u-pecl-memcached available.
No package php55u-pecl-redis available.
No package php55u-pecl-xdebug available.
No package php55u-pecl-imagick available.
No package php55u-pecl-mongo available.
```

So far, other than those missing modules, things look good (only quickly verified that PHP ran phpinfo(), haven't had a chance to run any further testing yet).

**Comment by carlwgeorge** [comment]
The php55u-pecl-apcu and php55u-pecl-igbinary EL7 packages have been completed.  I'll address the remaining ones soon.

**Comment by carlwgeorge** [comment]
The php55u-pecl-memcached and php55u-pecl-redis EL7 packages have been completed.

**Comment by carlwgeorge** [comment]
I've been busy with other things, but I'm ready to get this wrapped up.  I'll keep editing this comment with my progress.

- [x] php55u
- [x] php55u-pear
- [x] php55u-pecl-jsonc
- [x] php55u-pecl-igbinary
- [x] php55u-pecl-apcu
- [x] php55u-pecl-memcached
- [x] php55u-pecl-redis
- [ ] php55u-pecl-memcache
- [ ] php55u-pecl-xdebug
- [ ] php55u-pecl-imagick
- [ ] php55u-pecl-mongo
- [ ] php55u-ioncube-loader
- [ ] php55u-pecl-geoip
- [ ] php55u-pecl-lzf
- [ ] php55u-pecl-pthreads
- [ ] php55u-pecl-uploadprogress
- [ ] php55u-suhosin

**Comment by carlwgeorge** [comment]
All the php55u packages are now in the EL7 testing repositories.  Please testing them and share your feedback.

**Comment by jonathanvaughn** [comment]
Everything appears to have built fine in our container using these packages, I'll update after a few days of testing, but so far it works as expected.

**Comment by carlwgeorge** [comment]
@jonathanvaughn How are the packages working out for you?

**Comment by jonathanvaughn** [comment]
I haven't had any complaints from our developers in the last 2 weeks, so I assume everything is working fine :) I guess we can close this now?

**Comment by carlwgeorge** [comment]
These builds will move to the stable repositories during tonight's automation.  Let us know if you see any issues.  Thanks for participating in IUS!
