### ISSUE TITLE
php70u-pecl-redis

### ISSUE THREAD

**Issue by fpswebmaster** [iuscommunity/wishlist#43]
I would like to request the PECL-REDIS for PHP-70u is added to IUS.

**Comment by carlwgeorge** [comment]
Howdy @fpswebmaster,

Thanks for the request.  We evaluate new package requests on a case-by-case basis.  Here is our basic evaluation criteria.

1. Is the new package a good fit for IUS?
2. Is the new package maintainable with our current resources?
3. Is the requester willing to test the new package to ensure it works as expected?

A few quick checks indicates that the redis module is not yet compatible with PHP 7.  Once upstream releases a PHP7-compatible stable version, we will take another look at packaging this.

**Comment by fpswebmaster** [comment]
Great! Yes I noticed there isn’t a compatible PHP7 release yet (which I found odd due to Redis’ performance and popularity).

I would be willing to test the new package on both my Development and Production environment once it is packaged.

Thank you in advance

On Feb 8, 2016, at 10:25 AM, Carl George <notifications@github.com<mailto:notifications@github.com>> wrote:


Howdy @fpswebmaster<https://github.com/fpswebmaster>,

Thanks for the request. We evaluate new package requests on a case-by-case basis. Here is our basic evaluation criteria.

  1.  Is the new package a good fit for IUS?
  2.  Is the new package maintainable with our current resources?
  3.  Is the requester willing to test the new package to ensure it works as expected?

A few quick checks indicates that the redis module is not yet compatible with PHP 7. Once upstream releases a PHP7-compatible stable version, we will take another look at packaging this.

—
Reply to this email directly or view it on GitHub<https://github.com/iuscommunity/wishlist/issues/43#issuecomment-181411904>.

________________________________

Notice: This email message, including any attachments, is for the sole use of the intended recipient(s). If you are not the intended recipient, please contact the sender by reply email and destroy all copies of the original message. Please note that messages may be subject to the Connecticut Freedom of Information Act and to the confidentiality provisions of the Family Education Rights and Privacy Act. (FPSdisclaimerv123)

**Comment by remicollet** [comment]
This extension is still in early development for PHP 7

But if you are crazy enough you can try the [php-pecl-redis](http://rpms.remirepo.net/enterprise/7/test70/x86_64/repoview/php-pecl-redis.html) from remi-test repository. (which could be download and installed manually and should work with php70w from IUS)

**Comment by Xon** [comment]
There is a [php7 branch](https://github.com/phpredis/phpredis/tree/php7) in development which appears fairly stable, which I've been using since early December.

But they haven't yet release a version marked as stable, and the last month has seen a scary number of memory leaks and php7 related fixes being put in.

**Comment by fpswebmaster** [comment]
Thanks @remicollet for the idea, I may try that on our DEV environment although real world sessions will be hard to simulate.

@Xon going through the commit logs for that branch it seems only a few changes were made to fix the memory leak issues. I'm curious as to what role PHP7 would have in create memory leaks & other various bugs versus the stable PHP5.6 builds.

Thanks again for the quick feedback.

**Comment by Xon** [comment]
@fpswebmaster php7 causes large changes for extension, some of them related to how memory objects are handled.

**Comment by carlwgeorge** [comment]
[Relevant upstream issue](https://github.com/phpredis/phpredis/issues/804).

**Comment by carlwgeorge** [comment]
Version 3.0.0 has been [tagged](https://github.com/phpredis/phpredis/releases/tag/3.0.0) and [uploaded to PECL](https://pecl.php.net/package/redis/3.0.0) as a stable release.  I've got an initial [spec file](https://github.com/iuscommunity-pkg/php70u-pecl-redis) finished.  However, 32bit builds fail.  I'm going to report the failure upstream, then skip it in our build so that way we can get the packages out there for more testing.

**Comment by carlwgeorge** [comment]
The [initial build](https://github.com/iuscommunity-pkg/php70u-pecl-redis/releases/tag/3.0.0-1.ius) have been completed and moved to the testing repositories.  We look forward to feedback so we can promote the package to the stable repositories.

**Comment by vasillalov** [comment]
Thank you very much for working on this! It is greatly appreciated! I do not see php70u-pecl-redis packages built in the testing repo. I checked both the CentOS 6 and CentOS 7 testing repos and I did not see it.

**Comment by carlwgeorge** [comment]
We had a small hiccup with our automation.  The packages should be available in our testing repositories at about 4 PM CDT (21:00 UTC).  Sorry for the delay.

**Comment by l0bster** [comment]
@vasillalov did you have time to test this module? Thanks for your feddback. I'm looking forward to this module too ;)

**Comment by vasillalov** [comment]
Hey folks,

We are already testing this on two clients. It looks like the module performs adequately. We are plan on performing load testing to find any potential bottle necks with this.

**Comment by b-harper** [comment]
Hey @vasillalov,

If I understand you correctly, the package is working correctly.  You just need to get some additional testing to tweak the configuration for your clients.  Is this correct?

-Ben

**Comment by vasillalov** [comment]
Correct. The package works correctly so far. What we are doing next is performing load tests and stress tests to determine throughput and bottlenecks and compare those results for php56u-pecl-redis metrics. Only then we'll know if we have a usable module that can be deployed for PROD environments.

**Comment by b-harper** [comment]
Thanks for the update.  Sounds like the packages are ready for the stable repositories.  This will happen after tonight's automation run.
