### ISSUE TITLE
replacement for Launchpad mailing list

### ISSUE THREAD

**Issue by b-harper** [iuscommunity/wishlist#44]
IUS has almost completely migrated off Launchpad. The only service we still use is low traffic [mailing list][0].  Over the years it was served a few different roles, but recently it has just an announce(ment) mailing list.  We are toying with the idea of creating a GItHub repository like the wishlist repository but for announcements.  While Github issues aren't the same a traditional mailing list,  it is easier that running mailman and dealing with spam. 

We are looking for feedback on this idea and/or see if there are any other solutions that might work better.

-Ben

[0]: https://lists.launchpad.net/ius-community/

**Comment by carlwgeorge** [comment]
Does anyone have any positive/negative experiences with [Librelist](http://librelist.com)?

**Comment by b-harper** [comment]
We have decided to proceed with this [announce GitHub repository][0] to replace the [general mailing list][1].  It is recommended that all IUS users watch that  repository for EOL and other important announcements.  


[0]: https://github.com/iuscommunity/announce
[1]: https://launchpad.net/%7Eius-community
