### ISSUE TITLE
Request mod24u_fastcgi, mod24u_fcgid, mod24u_ruid2 and mod24u_suphp

### ISSUE THREAD

**Issue by mustafaramadhan** [iuscommunity/wishlist#45]
I would like to request mod24u_fastcgi, mod24u_fcgid, mod24u_ruid2 and mod24u_suphp for httpd24u are added to IUS.

**Comment by carlwgeorge** [comment]
Hello @mustafaramadhan,

Please open these as separate requests, since we will consider them independently.
