### ISSUE TITLE
Please build python35u-mod_wsgi

### ISSUE THREAD

**Issue by rtprio** [iuscommunity/wishlist#50]
Please build python35u-mod_wsgi for centos 6. I have a few x86_64 systems ready to test it with.

Also, thank you for all your work keeping these maintained.

**Comment by b-harper** [comment]
@rtprio,

Thanks for taking the time to submit this request.  We can not promise that we will proceed with every request, so we came up with these questions to help evaluate requests:

* Is the new package a good fit for IUS?
* Will the new package be maintainable with our current resources?
* Is the requester willing to test the new package to ensure expected behavior?

This package would be a good fit for IUS and should be maintainable, as we mod_wsgi  for other versions of Python.  We will look to get some initial packages into the testing repositories soon.

**Comment by b-harper** [comment]
@rtprio, 

Initial packages have been built and will hit the testing repositories during tonight's automation run.  Let us know if they work your for needs.

**Comment by rtprio** [comment]
@b-harper 

Thank you for building this so quickly.  I've had a chance to test, but am getting the following message:

```
# apachectl configtest
httpd: Syntax error on line 196 of /etc/httpd/conf/httpd.conf: Syntax error on line 3 of /etc/httpd/conf.d/python35u-mod_wsgi.conf: 
Cannot load /etc/httpd/modules/python35u-mod_wsgi.so into server: /etc/httpd/modules/python35u-mod_wsgi.so: undefined symbol: PyExc_StopIteration
```

I'm not familiar with that error, but I do notice that `/usr/lib64/httpd/modules/python35u-mod_wsgi.so` is not linked to libpython. It would appear that `--library python3.5m` may not be doing what it claims to?

```
# export LD_PRELOAD=/usr/lib64/libpython3.5m.so.1.0
# apachectl configtest
...
[Tue Feb 23 09:21:50 2016] [warn] VirtualHost localhost:8008 overlaps with VirtualHost localhost:8008, the first has precedence, perhaps you need a NameVirtualHost directive
Syntax OK
```

I'm surprised that worked.

**Comment by carlwgeorge** [comment]
I am able to reproduce that error.  I know upstream Python made some changes to the location/name of the libpython library in 3.5.  Let me get my head back in that Makefile and see if I can sort out what the issue is.

**Comment by carlwgeorge** [comment]
We've overhauled the package to bring it in line with Fedora, including:

* configure and make flags
* module and configuration file names

Using this new package, `apachectl configtest` passes, and I can get a basic hello world wsgi app to work.

##### `/etc/httpd/conf.d/hello.conf`
```apache
WSGIScriptAlias / /var/www/html/hello.wsgi
```
##### `/var/www/html/hello.wsgi`
```python
def application(environ, start_response):
    status = '200 OK'
    output = 'Hello World!'

    response_headers = [('Content-type', 'text/plain'),
                        ('Content-Length', str(len(output)))]
    start_response(status, response_headers)

    return [output.encode('utf-8')]
```



The new package will move to the testing repositories during tonight's automation.

**Comment by rtprio** [comment]
This is working well for me, thanks!

**Comment by carlwgeorge** [comment]
Thanks for getting back to us.  I tagged this to move to the stable repositories during tonight's automation.  Thanks for participating in IUS!
