### ISSUE TITLE
requesting php70u-sqlite3

### ISSUE THREAD

**Issue by christopherowen** [iuscommunity/wishlist#55]
### What package do you want?

php70u-sqlite3

### Why?

it's a dependency for phan (https://www.github.com/etsy/phan)

### OS versions

I would like this package for both RHEL 6 and 7.

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by christopherowen** [comment]
unfortunately, it says that I need a minimum version of 0.7-dev and I'm not certain if that flies in the face of the packaging policy here.

**Comment by christopherowen** [comment]
actually, it may normally come with php 7.  Perhaps it was disabled for the build in php70u.

https://github.com/php/php-src/tree/master/ext/sqlite3

**Comment by carlwgeorge** [comment]
The sqlite3 extension is provided by the pdo subpackage.

```
# repoquery --whatprovides php70u-sqlite3
php70u-pdo-0:7.0.4-1.ius.centos7.x86_64
```

**Comment by christopherowen** [comment]
I have never seen the repoquery command before.

Thank you for the lesson and pointer!

**Comment by christopherowen** [comment]
I have never seen the repoquery command before.

Thank you for the lesson and pointer!

**Comment by christopherowen** [comment]
I have never seen the repoquery command before.

Thank you for the lesson and pointer!

**Comment by christopherowen** [comment]
I have never seen the repoquery command before.

Thank you for the lesson and pointer!

**Comment by christopherowen** [comment]
I have never seen the repoquery command before.

Thank you for the lesson and pointer!

**Comment by christopherowen** [comment]
I have never seen the repoquery command before.

Thank you for the lesson and pointer!

**Comment by christopherowen** [comment]
I have never seen the repoquery command before.

Thank you for the lesson and pointer!

**Comment by christopherowen** [comment]
I have never seen the repoquery command before.

Thank you for the lesson and pointer!

**Comment by christopherowen** [comment]
I have never seen the repoquery command before.

Thank you for the lesson and pointer!

**Comment by christopherowen** [comment]
I have never seen the repoquery command before.

Thank you for the lesson and pointer!

**Comment by christopherowen** [comment]
I have never seen the repoquery command before.

Thank you for the lesson and pointer!

**Comment by christopherowen** [comment]
I have never seen the repoquery command before.

Thank you for the lesson and pointer!

**Comment by carlwgeorge** [comment]
Yeah repoquery is pretty nice, it's part of the yum-utils package.  It's extremely useful for package maintainers, and is a great tools for sysadmins as well.  Some more examples:

```
# repoquery --whatprovides /usr/bin/repoquery
yum-utils-0:1.1.31-34.el7.noarch
yum-utils-0:1.1.31-29.el7.noarch
```
```
# repoquery --whatprovides php-sqlite3
php70u-pdo-0:7.0.4-1.ius.centos7.x86_64
php56u-pdo-0:5.6.19-1.ius.centos7.x86_64
php-pdo-0:5.4.16-36.el7_1.x86_64
```
```
# repoquery --whatprovides php-zip
php-common-0:5.4.16-36.el7_1.x86_64
php56u-common-0:5.6.19-1.ius.centos7.x86_64
php70u-common-0:7.0.4-1.ius.centos7.x86_64
```
```
# repoquery --whatprovides redis
redis-0:2.8.19-2.el7.x86_64
redis30u-0:3.0.7-1.ius.centos7.x86_64
```
```
# repoquery --whatprovides /usr/bin/python3.5
python35u-0:3.5.1-2.ius.centos7.x86_64
```
```
# repoquery --whatprovides httpd
httpd-0:2.4.6-40.el7.centos.x86_64
httpd24u-0:2.4.18-3.ius.centos7.x86_64
```
```
# repoquery --whatprovides webserver
nginx-1:1.6.3-8.el7.x86_64
httpd-0:2.4.6-40.el7.centos.x86_64
httpd24u-0:2.4.18-3.ius.centos7.x86_64
lighttpd-0:1.4.39-1.el7.x86_64
```
