### ISSUE TITLE
php56u-pecl-ssh2

### ISSUE THREAD

**Issue by immanetize** [iuscommunity/wishlist#58]
### What package do you want?

pecl's ssh2 module, for whichever versions of PHP that IUS ships and the module is viable with.

### Why?

Applications like WordPress can use this library for uploading plugins and static assets, often obviating the need for an FTP daemon.  Reducing the need for FTP reduces compromise risk to the server; I think legacy FTP should be avoided everywhere these days, and the availability of this package furthers that goal.

Note that the package is available in EPEL, although only for stock php.  Although the maintainers *still* have not tagged a release as 'stable', problems reported via RHBZ and upstream github are minimal.  Some recent upstream activity suggests the module is still cared for, and growing support for php7.

### OS versions

I would like this package for both RHEL 6 and 7.

### Testing

I agree to test the new package to ensure that it works as expected, for each permutation of OS and PHP version.

**Comment by carlwgeorge** [comment]
Howdy @immanetize!  Thanks for reaching out.  We've gotten a request for this before (#23).  As you pointed out, there still isn't a release marked as "stable" by upstream, but there has been recent commit activity.  I'm going to do some research to determine if an exception to our stable rule is appropriate.

**Comment by carlwgeorge** [comment]
I found [this upstream bug](https://bugs.php.net/bug.php?id=68459) asking for a stable release.  There has been no reply since 2014, but I voted on it.

Hey @langemeijer, I noticed you have some recent activity on [php/pecl-networking-ssh2](https://github.com/php/pecl-networking-ssh2).  Would you be willing to create a stable PHP5 compatible release that we can create an RPM package for?

**Comment by langemeijer** [comment]
I created stable release 0.13 for ssh2. This is php5 only.

**Comment by carlwgeorge** [comment]
I have built php56u-pecl-ssh2 and it will move to the testing repositories during tonight's automation.

**Comment by carlwgeorge** [comment]
@immanetize Any update on testing this?

**Comment by jnk0** [comment]
@carlwgeorge We have tested the package on various CentOS 7.2 hosts and it works as expected.

**Comment by carlwgeorge** [comment]
@jnk0 Thanks for helping with testing.

This package will move to the stable repositories during tonight's automation.
