### ISSUE TITLE
httpd24u 2.4.19/2.4.20

### ISSUE THREAD

**Issue by jren207** [iuscommunity/wishlist#63]
### What package do you want?

httpd24u (2.4.19, possibly 2.4.20)

### Why?

In 2.4.19, the following issue is fixed:

>   *) mod_proxy_fcgi: Suppress HTTP error 503 and message 01075, 
>      "Error dispatching request", when the cause appears to be 
>      due to the client closing the connection. 
>      PR58118.  [Tobias Adolph <adolph lrz.de>]

This would solve an issue I am having, in 2.4.18, between php-fpm and apache timing out, causing a 503 error.

I notice 2.4.20 is now out, so maybe building 2.4.20 at this moment might be more appropriate, although not essential.

### OS versions

I would like this package for RHEL/CentOS 7.

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by b-harper** [comment]
Hey @jren207,

Thanks for taking the time to create this issue.  We already package httpd24u.  Currently, 2.4.18 is in the stable repositories and 2.4.20 is in the testing repositories.  See our [release policy][0] for information on how we handle new releases.

If you need to report an issue for an existing package, please create an issue in the package repository within the [iuscommunity-pkg organization][1].  

-Ben  

[0]: https://ius.io/Philosophy/#release-policy
[1]: https://github.com/iuscommunity-pkg
