### ISSUE TITLE
AltArch support (ppc64)

### ISSUE THREAD

**Issue by sbuelow** [iuscommunity/wishlist#68]
### What package do you want?

PHP 5.5+ and Python 3.4+ for ppc64 mostly.
### Why?

I understand that ppc64 and ppc64le are a niche compared to x86 and x86_64, but nevertheless would be really useful to update stock packages also on these architectures. 
### OS versions

RHEL 7 and CentOS 7.
### Testing

I agree to test the new package to ensure that it works as expected. 
I'm available also for building and packaging process.

**Comment by b-harper** [comment]
Hey @sbuelow,

Thanks for taking the time to contact us regarding this request.  The focus of IUS has always been closely tied with web hosting.   Our project is [sponsored by Rackspace and was created my Rackers][0].  Currently, Rackspace donates both dedicated servers and Cloud services that power IUS and Rackspace do not have any ppc64 and ppc64le products as part of their standard offerings (along with most other hosting companies). 

Our x86_64 gear is unable to create packages for ppc64 or ppc64le:
 
```
$ mock -r epel-6-ppc64 SRPMS/curl-7.29.0-25.src.rpm 
ERROR: Cannot build target ppc64 on arch x86_64, because it is not listed in legal_host_arches ('ppc64',)
```
```
$ mock -r fedora-rawhide-ppc64le SRPMS/curl-7.29.0-25.src.rpm 
ERROR: Cannot build target ppc64le on arch x86_64, because it is not listed in legal_host_arches ('ppc64le',)
```
Even if we had the hardware, there are several other time consuming logistical issues that would need to be worked out before we could offer ppc64 and ppc64le.  Unfortunately, we would need to see considerable interest in these architectures before we could consider this request.  That being said, [our SRPMs are available][1].

-Ben

[0]: https://ius.io/History/#project-history
[1]: https://dl.iuscommunity.org/pub/ius/stable/CentOS/7/SRPMS/

**Comment by sbuelow** [comment]
Hey Ben
I will give it a try with mock and SRPMS for ppc64 and report back.
If it works out, I'll be happy to share the packages with Community.
Best Regards

-Stefano

**Comment by b-harper** [comment]
@sbuelow,

I would be interested in hearing about your experience.  All this talk of PPC is making me reminisce about my old PPC powered [P-P-P-P-Powerbook][0]. 


[0]: http://www.hot.ee/ppppowerbook/

**Comment by b-harper** [comment]
Hey @sbuelow,

I am curious if you had a chance to attempt to build these packages.  Keep us in the loop.

**Comment by sbuelow** [comment]
Hey @b-harper,
Still had no chance to try, I'm waiting for a development environment to test. I'll let you know as soon as I manage to build.
Best regards

**Comment by b-harper** [comment]
I am clearing out stale issues and closing them.  If this issues gets updated, we can open it again.
