### ISSUE TITLE
php55-suhosin.x86_64

### ISSUE THREAD

**Issue by Cheechy** [iuscommunity/wishlist#7]
Would it be possible to get suhosin compiled and included for php55?

We seem to have it for php54:
Name        : php54-suhosin
Arch        : x86_64
Version     : 0.9.37.1
Release     : 1.ius.centos6
Size        : 70 k
Repo        : ius
Summary     : Suhosin is an advanced protection system for PHP installations
URL         : http://www.hardened-php.net/suhosin/
License     : PHP
Description : Suhosin is an advanced protection system for PHP installations. It was designed
            : to protect servers and users from known and unknown flaws in PHP applications
            : and the PHP core.

The above looks like the latest release :)
We just started to upgrade our servers to use php55 though and would love to carry on using suhosin for security.

**Comment by cgtx** [comment]
Howdy Cheechy,

Thanks for reaching out!  Here is our review process for new package requests.

1. Is it a good fit for IUS?
2. Is it maintainable with our current resources?
3. After building the package, is the requester willing to test the package to ensure expected behavior?

I feel it is a good fit for IUS, and also maintainable.  I'll start working or porting the SPEC file.  Please reply that you agree to test once the initial RPMs are created.

**Comment by Cheechy** [comment]
Very happy to test if/when available!

**Comment by cgtx** [comment]
SPEC file in progress...

https://github.com/iuscommunity-pkg/php55u-suhosin

**Comment by cgtx** [comment]
Initial packages have been built and will move into our testing repos during tonight's automation.  If using the ius-release package, you will be able to install them with this command.

    yum --enablerepo=ius-testing install php55u-suhosin

There may be a delay while your local mirror syncs.

We don't necessarily need you to test every feature, just use the RPM how you normally would and give us a basic "works for me" / "doesn't work for me" response.

**Comment by Cheechy** [comment]
Works great for me!
Thank you for quickly sorting this. We have a lot more servers to roll out
php55 to and this will be needed for them all. Appreciate all the work :)

**Comment by cgtx** [comment]
Excellent, thanks for the quick reply.  I'll tag it to move to the stable repos with tonight's automation.
