### ISSUE TITLE
Update to 

### ISSUE THREAD

**Issue by appcove** [iuscommunity/wishlist#76]
### What package do you want?

python35u-postgresql

### Why?

This commit fixes a bug in the jsonb support for postgresql 9.5

https://github.com/python-postgres/fe/commit/2f2df7a3abf06f032b05122677a1937032b51a9c

Note that you must pass a JSON string, there's no json.dumps/loads magic.
In foobar 2.0.0, the --whiz-bang flag was added.  This feature would be very
useful to me.  RHEL 6 only has foobar 1.7.8, and RHEL 7 only has foobar 1.8.1.

### OS versions

I would like this package for both RHEL 6 and 7 (and Centos)

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by carlwgeorge** [comment]
Howdy @appcove,

I'm not sure I follow this request.  We already package python35u-postgresql, and it has been released to the stable repositories.  If you need to report a bug or request a feature, please submit a bug on [the appropriate repository](https://github.com/iuscommunity-pkg/python35u-postgresql/issues).  This one is only for new package requests.
