### ISSUE TITLE
php-pecl-ssh2

### ISSUE THREAD

**Issue by jnk0** [iuscommunity/wishlist#79]
### What package do you want?

php-pecl-ssh2 (https://pecl.php.net/package/ssh2)

### Why?

The PECL extension ssh2 is missing in IUS repo.  Base repo has it, but this 
package can't be installed if you use a newer PHP version (from IUS).  I would 
want php-pecl-ssl for PHP 5.6 and PHP 7.0 (different versions).

### OS versions

I would like this package for both RHEL 7.

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by carlwgeorge** [comment]
Howdy @jnk0,

We currently have another request for [php56u-pecl-ssh2](https://github.com/iuscommunity/wishlist/issues/58) that is in our testing repos.  Once it receives some positive testing feedback, we will move it to the stable repo.  The original requester hasn't replied yet, but if you want to test it and reply there it would be sufficient.

As far as PHP 7.0, this module does not have a PHP7 compatible stable release yet.  IUS has a strong preference to only package upstream stable releases.

**Comment by jnk0** [comment]
@carlwgeorge Thx, I have tested the package and posted a comment.
