### ISSUE TITLE
uwsgi-plugin_php70u 

### ISSUE THREAD

**Issue by Heidistein** [iuscommunity/wishlist#80]
### What package do you want?

uwsgi-plugin_php70u 
(and mod_proxy_uwsgi24u)
Basicly a rebuild of uwsgi against  the packages in the IUS repo.

### Why?

I would like to run PHP in a uwsgi container. Next to that in the feature also python and maybe others. Using the PHP from the IUS it would be nice to have the corresponding packages.

### OS versions

Could you build it for slackware? And CentOS7 please :)

### Testing

I agree to test the new package to ensure that it works as expected. For sure! :)

**Comment by carlwgeorge** [comment]
Howdy @Heidistein,

Thanks for opening a request with us.  I have completed an initial [spec file](https://github.com/iuscommunity-pkg/uwsgi-plugin-php70u) for this package.  The package should be available in our testing repositories after tonight's automation.

**Comment by Heidistein** [comment]
Sorry for this delay. We had lots of work on our hands.
We tested this plugin, and it is working as expected!

**Comment by b-harper** [comment]
Thanks for for the feedback.  This package will get moved to the stable repositories during the tonight's automation run.
