### ISSUE TITLE
mod_proxy_http2

### ISSUE THREAD

**Issue by stylobille** [iuscommunity/wishlist#84]
### What package do you want?

Hello, could you please add to your repository the module mod_proxy_http2 (for RHEL7 / EPEL7) ?
### Why?

So far I'm using your httpd24u (with HTTP 2.0 enabled) + php 7 and I'd like to try some things out with the mod proxy for http 2.0 which isn't provided so far.
https://httpd.apache.org/docs/current/fr/mod/mod_proxy_http2.html
### OS versions

I would like this package for RHEL 7.
### Testing

I agree to test the new package to ensure that it works as expected.

Thank you !

**Comment by Xon** [comment]
This request is dependant on https://github.com/iuscommunity/wishlist/issues/70

**Comment by b-harper** [comment]
Hey @stylobille,

Thanks for taking the time to submit this request.  We try to avoid requests like 'I don't have a need for X, but I think it would be cool if you packaged it'.  With limited resources, we want to make sure the effort to build and maintain packages are going to toward packages that are going to get used.  If you are just looking to try out the mod_proxy_http2 module, I would recommend using apxs (from httpd24u-devel) to compile the module on a test server. 

@Xon, thanks for cross linking this request with SSL thread. 

-Ben

**Comment by b-harper** [comment]
I am clearing out stale issues and closing them.  If this issue gets updated, we can open it again.
