### ISSUE TITLE
Please add uwsgi-plugin-python35u

### ISSUE THREAD

**Issue by intgr** [iuscommunity/wishlist#90]
### What package do you want?

uwsgi-plugin-python35u 2.0.13.1

### Why?

EPEL provides a uWSGI package version 2.0.13.1, but their plugins are built against an older version of Python. I would like to use uWSGI with IUS's python35u.

This is related to issue #11, where you state:
>  If you want us to give it another shot in the future such as with the python35u stack, just open a new issue and we'll take another look.

### OS versions

I would like this package for CentOS 7.

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by carlwgeorge** [comment]
Howdy @intgr,

Thanks for opening this request.  Sorry I mispoke in #11 and gave the impression that this request should be opened on that repo.  We have this dedicated wishlist repo for new package requests.

I am working on a spec file for this now.  Since we package python35u for both EL6 and EL7, I'm going to try to build it for both.

**Comment by carlwgeorge** [comment]
[Spec file](https://github.com/iuscommunity-pkg/uwsgi-plugin-python35u) complete, and builds are in progress.

**Comment by carlwgeorge** [comment]
Builds are complete.  The RPMs will move to the testing repositories during tonight's automation.  Let us know how your testing goes.

**Comment by intgr** [comment]
That was quick, thanks a lot! Tested and everything works as expected if I run `uwsgi --plugin=python35u`

> Sorry I mispoke in #11 and gave the impression that this request should be opened on that repo

No, that was my fault, I didn't notice the wishlist link on the website when I wrote that. :)

**Comment by carlwgeorge** [comment]
Glad to hear it's working as expected.  I'll move it to the stable repos on Monday.  Thanks for participating in IUS!
