### ISSUE TITLE
dovecot 2.2.25 , dovecot-pigeonhole v0.4.15, dovecot-mysql 2.2.25

### ISSUE THREAD

**Issue by clickbg** [iuscommunity/wishlist#91]
### What package do you want?

dovecot 2.2.25(Latest stable)
dovecot-pigeonhole v0.4.15(Latest stable)
dovecot-mysql 2.2.25(Latest stable)

### Why?

Current version of dovecot in RHEL 7 base is 2.2.10 which is 3 years behind the latest upstream - 2.2.25.
There are numerous features and security related bugfixes in the realeases between 2.2.10 and 2.2.25.
Some of them are: better replication, ability to use DH larger than 1024, faster indexing, lower memory footprint.

### OS versions

I would like this package for RHEL 7.
Note: It might be build for RHEL 6 however the RHEL 6 base uses dovecot 1.x. Migrating from 1.x to 2.2. is not trivial. Unfortunately we don`t have test/pre-production systems on RHEL6 so we cannot test a package there. But if there is big interest we might setup some systems for testing.

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by b-harper** [comment]
Hey @clickbg,

Thanks for taking the time to submit this issue.  With limited resources, we vet new requests before we are on the hook to maintain them for the long haul.  We want to avoid requests asking for the latest version just for the sake of having the latest version.  Red Hat does [backport security fixes][0], so there is no need to upgrade for security.  You mentioned that there are new features, but it is unclear if you need any of those features.   Are there features you are needing in the latest dovecot?  A quick peek at Fedora's SRPM (we stand on the shoulders of giants) shows they are using pigeonhole v0.4.14.  Could that version work for your need?

[0]: https://access.redhat.com/security/updates/backporting/

**Comment by clickbg** [comment]
Hi,

One very important feature for us is to be able to use DH parms larger than 1024 in order to prevent the Logjam attack. This was fixed upstream in year 2014 version 2.2.15 but RH never back-ported it - you can see that commit 6efd7ab25b71 is not the RH distributed code.
Reference: http://dovecot.org/pipermail/dovecot-cvs/2014-November/025209.html

Other new feature present only in 2.2.25 which we are planing to implement is the external policy server - http://wiki2.dovecot.org/Authentication/Policy

Fedora 24 currently distributes 2.2.24 so the SRPMs from there can be recompiled for RH/CentOS. 
Fedora 25 will be shipping 2.2.25 - at least according to rawhide. 
The pigeonhole plugin however should always match the Dovecot version, so if you compile Pigeonhole v0.4.14(the one in Fedora stable) you will need to compile Dovecot 2.2.24.
Reference: https://mirrors.uni-ruse.bg/fedora/linux/releases/24/Everything/x86_64/os/Packages/d/

**Comment by b-harper** [comment]
Hey @clickbg,

Thanks for the additional information.  We will take a closer look at packing dovecot.

**Comment by b-harper** [comment]
@clickbg,

I am unable to find any documentation regarding the versioning of pigeonhole and Dovecot itself.  Looking at the current [Fedora spec file][0], it shows Dovecot 2.2.25 and pigeonhole 0.4.14.  You would happen to know where I can find out more information about the versioning of pigeonhole and Dovecot itself?

Also note, Dovecot has moved away from their [self hosted mercurial instance][1] to [GitHub][2].  [This][3] is the commit for the DH parms on GitHub.





[0]: http://pkgs.fedoraproject.org/cgit/rpms/dovecot.git/tree/dovecot.spec
[1]: http://hg.dovecot.org/
[2]: https://github.com/dovecot
[3]: https://github.com/dovecot/core/commit/7ef7f34c38954020004e2b25b4ce8f54b4bcf8f3

**Comment by clickbg** [comment]
Hi,

The Pigeonhole is hosted on GitHub as a sub-project of dovecot - https://github.com/dovecot/pigeonhole
The relation between the versioning is a bit strange, you can find the correct Pigeonhole version for given Dovecot version by looking at the release notes for Pigeonhole. Those can be found only in the Dovecot mailing list(as far as I can see). 

For Dovecot 2.2.25 and Pigeonhole v0.4.15  - http://www.dovecot.org/list/dovecot-news/2016-July/000325.html
For Dovecot 2.2.24 and Pigeonhole v0.4.14 - http://www.dovecot.org/list/dovecot-news/2016-April/000321.html

I guess the RHEL packagers wanted to make it a bit more clear to the users and so the dovecot and dovecot-pigeonhole rpms have the same version in the official repo. In fact all the dovecot plugins have the Dovecot version in their rpm name.

**Comment by b-harper** [comment]
Thanks. I got looking all over the [Dovecot][0] and [pigeonhole][1] sites and could not find any information.  I didn't think to look through the mailing list archive to get this key piece of information.

Currently, both the Fedora and RHEL package maintainers use a single SRPM to create the main dovecot package and the plugins as sub packages.  Using this technique the versions are the same.  A different SRPM would be needed, if they wanted to reflect the different version numbers.  


[0]: http://dovecot.org/
[1]: http://pigeonhole.dovecot.org

**Comment by b-harper** [comment]
Some initial packages have been built and will hit the testing repositories after tonight's automation run.

**Comment by clickbg** [comment]
Hi,

Superb! Thanks a lot!
Below are my test results.

I just installed the following packages from ius-testing:

dovecot22u-2.2.25-1.ius.el7.x86_64
dovecot22u-mysql-2.2.25-1.ius.el7.x86_64
dovecot22u-pigeonhole-2.2.25-1.ius.el7.x86_64

Test environment:
2 KVM VMs - one in East Europe and one in West Europe
Dovecot master-master replication without Director
MySQL master-master replication
OS: CentOS Linux release 7.2.1511 
MySQL version: mysql  Ver 15.1 Distrib 10.1.17-MariaDB (From IUS Stable)
Postfix version: 2.10.1-6 
Number of users: 25
AWS Route53 used for directing the clients from the primary instance to the secondary in case the primary one is down.

Installation: No issues
Backup configs, remove dovecot from 2nd replica, install dovecot22u and pigeonhole,mysql plugins from IUS Testing. Restore configs. Start 2nd replica, trigger Route53 fail-over, repeat on primary replica.

Replication: No issues
IMAP/IMAPS: No issues
Sieve/Managesieve: No issues

I was also able to rise the ssl_dh_parameters_length above 1024 thus avoiding Logjam.

So it works great!
Unfortunately I am unable to test the postgresql plugin as we don`t have any postgresql DBs.
If you want me to test something else please write here.

Thanks again!

**Comment by b-harper** [comment]
Thanks for the very detailed testing.  We will push these packages to the stable repositories during tonight's automation run.
