### ISSUE TITLE
php70u-ioncube-loader

### ISSUE THREAD

**Issue by mhayes14** [iuscommunity/wishlist#92]
### What package do you want?

php70u-ioncube-loader
### Why?

The ionCube Loader now [supports PHP 7](http://blog.ioncube.com/2016/09/15/php-7-ioncube-loaders/), this will allow users of ionCube encoded scripts to upgrade to PHP7.
### OS versions

I would like this package for RHEL/CentOS 7.
### Testing

I agree to test the new package as an ionCube encoded script end user to ensure that it works as expected.

**Comment by karljohns0n** [comment]
I was about to create this issue. IonCube 6.0.4 now supports PHP 7 and has been in QA for few months. Please consider building this package.

**Comment by carlwgeorge** [comment]
Thanks for opening this request.  It appears that PHP7 support has not yet been declared stable upstream.  The stable release is version 5.1.2, but PHP7 support was added in version 6.0.1 (labeled as "latest").  Further confirming this is the fact that the tarball name for stable release includes the version number ([ioncube_loaders_lin_x86-64_5.1.2.tar.gz](http://downloads3.ioncube.com/loader_downloads/ioncube_loaders_lin_x86-64_5.1.2.tar.gz)), but the "latest" release does not ([ioncube_loaders_lin_x86-64.tar.gz](http://downloads3.ioncube.com/loader_downloads/ioncube_loaders_lin_x86-64.tar.gz)).  This unversioned tarball would be difficult to package, as the version could vary depending on when it was downloaded.  Additionally, unversioned tarballs typically indicate a version control snapshot, which would be even further away from a stable or even an alpha/beta/RC release.

IUS stands for **I**nline with **U**pstream **S**table.  Consider all the factors, we would prefer to put this request on hold until PHP7 support is available in a stable release from ionCube.

**Comment by mhayes14** [comment]
Thanks, noted. I will monitor and update this issue when the 6.x release is considered stable.

**Comment by mhayes14** [comment]
I'm not sure what the actual criteria is for considering a package to be stable. However ionCube have recently changed their [download page](http://www.ioncube.com/loaders.php) and it looks as though they consider v6.0 to be stable now. References to "latest" and "stable" versions have been removed, along with references to v5. Instead only v6.0.5 is available.

In regards to the filenames, although the linked files on the downloads page are unversioned, the versioned filenames do also exist e.g. [ioncube_loaders_lin_x86-64_6.0.4.tar.gz](http://downloads3.ioncube.com/loader_downloads/ioncube_loaders_lin_x86-64_6.0.4.tar.gz) and [ioncube_loaders_lin_x86-64_6.0.5.tar.gz](http://downloads3.ioncube.com/loader_downloads/ioncube_loaders_lin_x86-64_6.0.5.tar.gz).

Previous downloads page for comparison: https://web.archive.org/web/20161012193247/http://www.ioncube.com/loaders.php

Thanks,
Mike

**Comment by b-harper** [comment]
Hey @mhayes14,

For most software we package, the upstream projects make it very clear if the version is alpha, beta, release candidate, stable, etc.   For Ioncube, it is not that clear as currently they do not have any labels.  Seeing that are versioned tarballs, I will look into getting some initial packages created.

**Comment by b-harper** [comment]
Initial packages have been built and will be placed into the testing repository after tonight's automation run.    Please let us know if these work for your needs.

**Comment by mhayes14** [comment]
Awesome, thanks very much. Will test this out and then update.

**Comment by b-harper** [comment]
Hey @mhayes14,

Just checking in to see if you had a chance to test these packages.

**Comment by mhayes14** [comment]
Hi @b-harper 

Sorry for the delay, I do appreciate you putting this together. I have been a bit (unexpectedly) busy recently. I should be able to begin testing this today and will update you.

Thanks

**Comment by mhayes14** [comment]
Just to update. I had no problems installing this package on CentOS 7 yesterday. We now have a website running while the module is loaded without problems, however this website isn't ioncube encoded. It will be the weekend when we migrate our ioncube encoded website to the new system, I'll confirm once this has been done without any problems. Thanks.

**Comment by mhayes14** [comment]
I can confirm the extension is working properly here for both installation and usage on CentOS 7.

Thanks!

**Comment by b-harper** [comment]
Thanks for the feedback.  The php70u-ioncube-loader packages will get moved into the stable repositories during tonight's automation.

**Comment by karljohns0n** [comment]
Can you guys also push this package for php71u?

**Comment by b-harper** [comment]
@karljohns0n,

We like to keep a single request per issue.  If you would like see php71u-ioncube-loader packages, please open a new issue,
