### ISSUE TITLE
php70u-pecl-apcu 5.1.6

### ISSUE THREAD

**Issue by guilhermeblanco** [iuscommunity/wishlist#93]
### What package do you want?

php70u-pecl-apcu 5.1.6 ( https://github.com/krakjoe/apcu/releases/tag/v5.1.6 )

### Why?

In php70u-pecl-apcu, several segmentation fault issues were resolved in combination with php-fpm. CentOS 7 only has php70u-pecl-apcu 5.1.5.

### OS versions

I would like this package for CentOS 7.

### Testing

Already tested released code by manually installing on a staging server and monitoring traffic for the last 24h.

**Comment by carlwgeorge** [comment]
This repository is only for requesting **new** packages.  We already package php70u-pecl-apcu.  Do not open issues here to ask for an update to an existing package.  We [track the upstream project](https://versiontracker.iuscommunity.org/packages/150/), so we know when new versions are available.  We [updated our spec file](https://github.com/iuscommunity-pkg/php70u-pecl-apcu/commit/bd5e972) yesterday, built the [new packages](https://github.com/iuscommunity-pkg/php70u-pecl-apcu/releases/tag/5.1.6-1.ius), and they moved into our [testing repository](https://dl.iuscommunity.org/pub/ius/testing/CentOS/7/x86_64/php70u-pecl-apcu-5.1.6-1.ius.centos7.x86_64.rpm) last night.  You can get the update now by running this command.

    yum --enablerepo ius-testing update php70u-pecl-apcu

If that doesn't work, then your local mirror has not yet synced the new files.
