### ISSUE TITLE
Scala

### ISSUE THREAD

**Issue by lxvi** [iuscommunity/wishlist#95]
### What package do you want?

scala latest stable

### Why?

Need to manage a development/production environment through yum

### OS versions

CentOS 7

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by carlwgeorge** [comment]
Howdy @lxvi,

Thanks for opening a request with us.  IUS is focused on providing newer versions of stock RHEL/CentOS software.  Scala is not currently packaged in stock RHEL/CentOS, so it would not be a good fit for IUS.  It is however already packaged in Fedora, so it's a great candidate for [EPEL](https://fedoraproject.org/wiki/EPEL).  I recommend you open a [bugzilla](https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora&component=scala&version=rawhide) and ask the Fedora maintainer to create an EPEL7 branch.
