### ISSUE TITLE
varnish5, varnish5-modules, gearmand11, virtuoso-opensource18

### ISSUE THREAD

**Issue by gboddin** [iuscommunity/wishlist#97]
### What package do you want?

varnish5 5.0.1
gearmand 1.1.14
php{56,70}-pecl-oci8
virtuoso-opensource72 7.2

### Why?
I kinda already started my own repo published by travis-ci but I see you guys are way further ! Can I propose to merge the package specs I already made at https://github.com/gboddin/edge-repo/tree/master/SPECS ?

### OS versions

I would like this package for both RHEL 6 and 7.

### Testing

I agree to test the new package to ensure that it works as expected. We use them in production ;)

**Comment by carlwgeorge** [comment]
Howdy @gboddin,

We already have an [existing request](https://github.com/iuscommunity/wishlist/issues/96) for the oci8 module, but it looks like there are significant licensing concerns with the build requirements, so it probably won't happen.

As far as the other packages, please open individual issues and we will investigate them separately.
